load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "lib",
    crate_name = "ctx_workspace_services",
    crate_root = "src/lib.rs",
    edition = "2021",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//core/crates/ctx-core:lib",
        "//core/crates/ctx-fs:lib",
        "@crates//:anyhow",
        "@crates//:chrono",
        "@crates//:directories",
        "@crates//:serde",
        "@crates//:tempfile",
        "@crates//:tokio",
        "@crates//:toml",
        "@crates//:tracing",
        "@crates//:uuid",
    ],
    proc_macro_deps = [
        "@crates//:async-trait",
    ],
)

rust_test(
    name = "unit_tests",
    crate = ":lib",
)
