# Generated by core/apps/web/scripts/generate-playwright-browser-lock.mjs
# Generated at: 2026-04-24T16:45:00.000Z
# Playwright version: 1.57.0

PLAYWRIGHT_BROWSER_RUNTIME_LOCK = {
    "mac15-arm64": {
        "chromium": {
            "directory_name": "chromium-1200",
            "sha256": "01046b12151b2846b6d34ff619336b6338ca254c47aacc903602dd96afc939b3",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-mac-arm64.zip",
        },
        "firefox": {
            "directory_name": "firefox-1497",
            "sha256": "fed31d85a35d117f28a67416b76e190e41e7e2ada66309266d89b9cb0d6d03ee",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/firefox/1497/firefox-mac-arm64.zip",
        },
        "webkit": {
            "directory_name": "webkit-2227",
            "sha256": "70a6d62ce9f0280c6a56e0b548e98b4eeebd29be047769a6381c23e568034f44",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/webkit/2227/webkit-mac-15-arm64.zip",
        },
    },
    "ubuntu22.04-x64": {
        "chromium": {
            "directory_name": "chromium-1200",
            "sha256": "ab56b2a7955c2961f74348e2349f1e907489283da23dba37c730b624e4d670bb",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-linux.zip",
        },
        "firefox": {
            "directory_name": "firefox-1497",
            "sha256": "4840492ad5bb2585db35c68c2d385d22708d23a04a12593f4553e7b769be3a03",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/firefox/1497/firefox-ubuntu-22.04.zip",
        },
        "webkit": {
            "directory_name": "webkit-2227",
            "sha256": "47c545a00fd6a25b821175ee8235e108dec043452ca93962a26b7d96b65397b1",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/webkit/2227/webkit-ubuntu-22.04.zip",
        },
    },
}
