# @generated by core/scripts/sync_rust_bazel_deps.cjs
# Source of truth: core/Cargo.toml via cargo metadata.
# Do not edit manually. Run `pnpm rust:bazel-deps:write` from core/.

RUST_BAZEL_DEPS = {
    "ctx-bundled-assets": struct(
        build_deps = [],
        deps = [
            "@crates//:serde",
            "@crates//:serde_json",
            "@crates//:tracing",
        ],
        dev_deps = [
            "@crates//:tempfile",
        ],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-core": struct(
        build_deps = [],
        deps = [
            "@crates//:chrono",
            "@crates//:serde",
            "@crates//:serde_json",
            "@crates//:uuid",
        ],
        dev_deps = [],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-crp-protocol": struct(
        build_deps = [],
        deps = [
            "@crates//:serde",
            "@crates//:serde_json",
        ],
        dev_deps = [],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-events": struct(
        build_deps = [],
        deps = [
            "@crates//:tokio",
        ],
        dev_deps = [],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-fs": struct(
        build_deps = [],
        deps = [
            "//core/crates/ctx-core:lib",
            "@crates//:anyhow",
            "@crates//:directories",
            "@crates//:tokio",
        ],
        dev_deps = [
            "@crates//:tempfile",
        ],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-harness-setup": struct(
        build_deps = [],
        deps = [
            "@crates//:serde",
        ],
        dev_deps = [],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-provider-accounts": struct(
        build_deps = [],
        deps = [
            "@crates//:anyhow",
            "@crates//:chrono",
            "@crates//:directories",
            "@crates//:serde",
            "@crates//:serde_json",
            "@crates//:tokio",
            "@crates//:tracing",
            "@crates//:uuid",
        ],
        dev_deps = [
            "@crates//:tempfile",
        ],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-provider-install": struct(
        build_deps = [],
        deps = [
            "@crates//:chrono",
            "@crates//:serde",
            "@crates//:tokio",
            "@crates//:uuid",
        ],
        dev_deps = [],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-provider-matrix": struct(
        build_deps = [],
        deps = [
            "//core/crates/ctx-provider-accounts:lib",
            "@crates//:anyhow",
            "@crates//:semver",
            "@crates//:serde",
            "@crates//:serde_json",
            "@crates//:tokio",
        ],
        dev_deps = [
            "@crates//:tempfile",
        ],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-runtime-assets": struct(
        build_deps = [],
        deps = [
            "//core/crates/ctx-harness-setup:lib",
            "@crates//:anyhow",
            "@crates//:flate2",
            "@crates//:fs2",
            "@crates//:futures",
            "@crates//:hex",
            "@crates//:reqwest",
            "@crates//:sha2",
            "@crates//:tar",
            "@crates//:tokio",
            "@crates//:url",
            "@crates//:zip",
            "@crates//:zstd",
        ],
        dev_deps = [
            "@crates//:tempfile",
        ],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-sandbox-contract": struct(
        build_deps = [],
        deps = [
            "//core/crates/ctx-core:lib",
            "@crates//:anyhow",
            "@crates//:serde",
            "@crates//:serde_json",
        ],
        dev_deps = [
            "@crates//:chrono",
            "@crates//:uuid",
        ],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-session-tools": struct(
        build_deps = [],
        deps = [
            "//core/crates/ctx-core:lib",
            "@crates//:chrono",
            "@crates//:serde_json",
            "@crates//:tracing",
        ],
        dev_deps = [],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-storage-admission": struct(
        build_deps = [],
        deps = [
            "@crates//:serde",
        ],
        dev_deps = [],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-worker-protocol": struct(
        build_deps = [],
        deps = [
            "@crates//:chrono",
            "@crates//:serde",
            "@crates//:uuid",
        ],
        dev_deps = [],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
    "ctx-workspace-active-snapshot": struct(
        build_deps = [],
        deps = [
            "//core/crates/ctx-core:lib",
            "@crates//:serde",
            "@crates//:serde_json",
            "@crates//:tokio",
        ],
        dev_deps = [
            "@crates//:chrono",
            "@crates//:uuid",
        ],
        dev_proc_macro_deps = [],
        proc_macro_deps = [],
    ),
}
