load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "lib",
    crate_name = "ctx_crp_protocol",
    crate_root = "src/lib.rs",
    edition = "2021",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "@crates//:serde",
        "@crates//:serde_json",
    ],
)
