import type { CSSProperties } from "react";

export const SESSION_THREAD_ROW_MAX_WIDTH_PX = 820;
export const SESSION_THREAD_HORIZONTAL_INSET_PX = 12;
export const SESSION_THREAD_INDENT_LEFT_PX = 4;
export const SESSION_THREAD_CONTENT_MAX_WIDTH_PX =
  SESSION_THREAD_ROW_MAX_WIDTH_PX - SESSION_THREAD_HORIZONTAL_INSET_PX * 2;
export const SESSION_THREAD_MARKDOWN_BODY_FONT_SIZE_PX = 13;
export const SESSION_THREAD_MARKDOWN_BODY_LINE_HEIGHT_PX = 20.15;
export const SESSION_THREAD_MARKDOWN_BODY_FONT_FAMILY =
  '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';
export const SESSION_THREAD_MARKDOWN_BLOCK_MARGIN_BOTTOM_PX = 12;
export const SESSION_THREAD_MARKDOWN_HEADING_MARGIN_TOP_PX = 16;
export const SESSION_THREAD_MARKDOWN_HEADING_MARGIN_BOTTOM_PX = 8;
export const SESSION_THREAD_MARKDOWN_LIST_INDENT_PX = 16.25;
export const SESSION_THREAD_MARKDOWN_LIST_GAP_PX = 4;
export const SESSION_THREAD_MARKDOWN_INLINE_CODE_PADDING_BLOCK_PX = 1;
export const SESSION_THREAD_MARKDOWN_INLINE_CODE_PADDING_INLINE_PX = 6;
export const SESSION_THREAD_MARKDOWN_INLINE_CODE_BORDER_WIDTH_PX = 1;
export const SESSION_THREAD_MARKDOWN_INLINE_CODE_BORDER_RADIUS_PX = 6;
export const SESSION_THREAD_MARKDOWN_INLINE_CODE_FONT_SIZE_PX =
  SESSION_THREAD_MARKDOWN_BODY_FONT_SIZE_PX;
export const SESSION_THREAD_MARKDOWN_INLINE_CODE_FONT_FAMILY =
  '"SF Mono", Menlo, Monaco, Consolas, "Courier New", monospace';
export const SESSION_THREAD_MARKDOWN_INLINE_CODE_EDGE_BLOCK_PX =
  SESSION_THREAD_MARKDOWN_INLINE_CODE_PADDING_BLOCK_PX + SESSION_THREAD_MARKDOWN_INLINE_CODE_BORDER_WIDTH_PX;
export const SESSION_THREAD_MARKDOWN_INLINE_CODE_EDGE_PX =
  SESSION_THREAD_MARKDOWN_INLINE_CODE_PADDING_INLINE_PX + SESSION_THREAD_MARKDOWN_INLINE_CODE_BORDER_WIDTH_PX;
export const SESSION_THREAD_MARKDOWN_INLINE_CODE_FRAGMENT_CHROME_HEIGHT_PX =
  SESSION_THREAD_MARKDOWN_INLINE_CODE_EDGE_BLOCK_PX * 2;
export const SESSION_THREAD_MARKDOWN_INLINE_CODE_FRAGMENT_CHROME_WIDTH_PX =
  SESSION_THREAD_MARKDOWN_INLINE_CODE_EDGE_PX * 2;
export const SESSION_THREAD_MARKDOWN_BLOCKQUOTE_BORDER_WIDTH_PX = 2;
export const SESSION_THREAD_MARKDOWN_BLOCKQUOTE_PADDING_INLINE_START_PX = 12;
export const SESSION_THREAD_MARKDOWN_BLOCKQUOTE_INSET_PX =
  SESSION_THREAD_MARKDOWN_BLOCKQUOTE_BORDER_WIDTH_PX + SESSION_THREAD_MARKDOWN_BLOCKQUOTE_PADDING_INLINE_START_PX;
export const SESSION_THREAD_MARKDOWN_IMAGE_WIDTH_PX = 240;
export const SESSION_THREAD_MARKDOWN_IMAGE_HEIGHT_PX = 180;
export const SESSION_THREAD_MARKDOWN_CODE_BLOCK_BORDER_WIDTH_PX = 1;
export const SESSION_THREAD_MARKDOWN_CODE_BLOCK_PADDING_TOP_PX = 28;
export const SESSION_THREAD_MARKDOWN_CODE_BLOCK_PADDING_BOTTOM_PX = 12;
export const SESSION_THREAD_MARKDOWN_TABLE_BORDER_WIDTH_PX = 1;
export const SESSION_THREAD_MARKDOWN_TABLE_CELL_PADDING_BLOCK_PX = 8;
export const SESSION_THREAD_MARKDOWN_TABLE_CELL_PADDING_INLINE_PX = 12;
export const SESSION_THREAD_MESSAGE_ROW_PADDING_BLOCK_PX = 6;
export const SESSION_THREAD_MESSAGE_BUBBLE_PADDING_BLOCK_PX = 10;
export const SESSION_THREAD_MESSAGE_BUBBLE_PADDING_INLINE_PX = 12;
export const SESSION_THREAD_MESSAGE_BUBBLE_BORDER_WIDTH_PX = 1;
export const SESSION_THREAD_MESSAGE_MAX_WIDTH_RATIO = 0.92;
export const SESSION_THREAD_MESSAGE_ROLE_FONT_SIZE_PX = 11;
export const SESSION_THREAD_MESSAGE_ROLE_LINE_HEIGHT_PX = 11;
export const SESSION_THREAD_MESSAGE_TOGGLE_MARGIN_TOP_PX = 6;
export const SESSION_THREAD_MESSAGE_TOGGLE_FONT_SIZE_PX = SESSION_THREAD_MARKDOWN_BODY_FONT_SIZE_PX;
export const SESSION_THREAD_MESSAGE_TOGGLE_LINE_HEIGHT_PX = 16;
export const SESSION_THREAD_MESSAGE_ATTACHMENT_WIDTH_PX = 240;
export const SESSION_THREAD_MESSAGE_ATTACHMENT_HEIGHT_PX = 180;
export const SESSION_THREAD_MESSAGE_ATTACHMENT_GAP_PX = 8;
export const SESSION_THREAD_MESSAGE_ATTACHMENT_MARGIN_TOP_PX = 8;

export const SESSION_THREAD_LAYOUT_STYLE = {
  "--wb-thread-max-width": `${SESSION_THREAD_ROW_MAX_WIDTH_PX}px`,
  "--wb-session-padding-inline": `${SESSION_THREAD_HORIZONTAL_INSET_PX}px`,
  "--wb-transcript-max-width": `${SESSION_THREAD_ROW_MAX_WIDTH_PX}px`,
  "--wb-markdown-body-font-size": `${SESSION_THREAD_MARKDOWN_BODY_FONT_SIZE_PX}px`,
  "--wb-markdown-body-line-height": `${SESSION_THREAD_MARKDOWN_BODY_LINE_HEIGHT_PX}px`,
  "--wb-markdown-body-font-family": SESSION_THREAD_MARKDOWN_BODY_FONT_FAMILY,
  "--wb-markdown-block-margin-bottom": `${SESSION_THREAD_MARKDOWN_BLOCK_MARGIN_BOTTOM_PX}px`,
  "--wb-markdown-heading-margin-top": `${SESSION_THREAD_MARKDOWN_HEADING_MARGIN_TOP_PX}px`,
  "--wb-markdown-heading-margin-bottom": `${SESSION_THREAD_MARKDOWN_HEADING_MARGIN_BOTTOM_PX}px`,
  "--wb-markdown-list-indent": `${SESSION_THREAD_MARKDOWN_LIST_INDENT_PX}px`,
  "--wb-markdown-list-gap": `${SESSION_THREAD_MARKDOWN_LIST_GAP_PX}px`,
  "--wb-markdown-inline-code-padding-block": `${SESSION_THREAD_MARKDOWN_INLINE_CODE_PADDING_BLOCK_PX}px`,
  "--wb-markdown-inline-code-padding-inline": `${SESSION_THREAD_MARKDOWN_INLINE_CODE_PADDING_INLINE_PX}px`,
  "--wb-markdown-inline-code-border-width": `${SESSION_THREAD_MARKDOWN_INLINE_CODE_BORDER_WIDTH_PX}px`,
  "--wb-markdown-inline-code-border-radius": `${SESSION_THREAD_MARKDOWN_INLINE_CODE_BORDER_RADIUS_PX}px`,
  "--wb-markdown-inline-code-font-size": `${SESSION_THREAD_MARKDOWN_INLINE_CODE_FONT_SIZE_PX}px`,
  "--wb-markdown-inline-code-font-family": SESSION_THREAD_MARKDOWN_INLINE_CODE_FONT_FAMILY,
  "--wb-markdown-blockquote-border-width": `${SESSION_THREAD_MARKDOWN_BLOCKQUOTE_BORDER_WIDTH_PX}px`,
  "--wb-markdown-blockquote-padding-inline-start": `${SESSION_THREAD_MARKDOWN_BLOCKQUOTE_PADDING_INLINE_START_PX}px`,
  "--wb-markdown-image-width": `${SESSION_THREAD_MARKDOWN_IMAGE_WIDTH_PX}px`,
  "--wb-markdown-image-height": `${SESSION_THREAD_MARKDOWN_IMAGE_HEIGHT_PX}px`,
  "--wb-markdown-table-border-width": `${SESSION_THREAD_MARKDOWN_TABLE_BORDER_WIDTH_PX}px`,
  "--wb-markdown-table-cell-padding-block": `${SESSION_THREAD_MARKDOWN_TABLE_CELL_PADDING_BLOCK_PX}px`,
  "--wb-markdown-table-cell-padding-inline": `${SESSION_THREAD_MARKDOWN_TABLE_CELL_PADDING_INLINE_PX}px`,
  "--wb-message-row-padding-block": `${SESSION_THREAD_MESSAGE_ROW_PADDING_BLOCK_PX}px`,
  "--wb-message-bubble-padding-block": `${SESSION_THREAD_MESSAGE_BUBBLE_PADDING_BLOCK_PX}px`,
  "--wb-message-bubble-padding-inline": `${SESSION_THREAD_MESSAGE_BUBBLE_PADDING_INLINE_PX}px`,
  "--wb-message-bubble-border-width": `${SESSION_THREAD_MESSAGE_BUBBLE_BORDER_WIDTH_PX}px`,
  "--wb-message-max-width": `${SESSION_THREAD_MESSAGE_MAX_WIDTH_RATIO * 100}%`,
  "--wb-message-role-font-size": `${SESSION_THREAD_MESSAGE_ROLE_FONT_SIZE_PX}px`,
  "--wb-message-role-line-height": `${SESSION_THREAD_MESSAGE_ROLE_LINE_HEIGHT_PX}px`,
  "--wb-message-toggle-margin-top": `${SESSION_THREAD_MESSAGE_TOGGLE_MARGIN_TOP_PX}px`,
  "--wb-message-toggle-font-size": `${SESSION_THREAD_MESSAGE_TOGGLE_FONT_SIZE_PX}px`,
  "--wb-message-toggle-line-height": `${SESSION_THREAD_MESSAGE_TOGGLE_LINE_HEIGHT_PX}px`,
  "--wb-message-attachment-width": `${SESSION_THREAD_MESSAGE_ATTACHMENT_WIDTH_PX}px`,
  "--wb-message-attachment-height": `${SESSION_THREAD_MESSAGE_ATTACHMENT_HEIGHT_PX}px`,
  "--wb-message-attachment-gap": `${SESSION_THREAD_MESSAGE_ATTACHMENT_GAP_PX}px`,
  "--wb-message-attachment-margin-top": `${SESSION_THREAD_MESSAGE_ATTACHMENT_MARGIN_TOP_PX}px`,
} as CSSProperties;

export function resolveSessionThreadRowWidth(viewportWidth: number): number {
  return Math.max(1, Math.min(SESSION_THREAD_ROW_MAX_WIDTH_PX, Math.floor(viewportWidth)));
}

export function resolveSessionThreadContentWidth(viewportWidth: number): number {
  return Math.max(1, resolveSessionThreadRowWidth(viewportWidth) - SESSION_THREAD_HORIZONTAL_INSET_PX * 2);
}
