use super::*;

pub(super) fn provider_routes() -> axum::Router<Arc<AppState>> {
    axum::Router::new()
        .route("/api/providers", get(list_providers))
        .route(
            "/api/providers/matrix/refresh",
            post(refresh_provider_matrix),
        )
        .route(
            "/api/providers/install_all",
            post(provider_launch::install_all_providers),
        )
        .route("/api/providers/:id", get(get_provider))
        .route("/api/providers/:id/usage", get(get_provider_usage))
        .route(
            "/api/providers/:id/harness_config",
            get(get_provider_harness_config),
        )
        .route(
            "/api/providers/:id/harness_config/select",
            post(select_provider_harness_source),
        )
        .route(
            "/api/providers/:id/harness_config/endpoints",
            post(upsert_provider_harness_endpoint),
        )
        .route(
            "/api/providers/:id/harness_config/endpoints/:endpoint_id",
            delete(delete_provider_harness_endpoint),
        )
        .route(
            "/api/providers/:id/harness_config/endpoints/:endpoint_id/models/refresh",
            post(refresh_provider_harness_endpoint_models),
        )
        .route(
            "/api/providers/:id/harness_config/endpoints/:endpoint_id/models/manual",
            put(set_provider_harness_endpoint_manual_models),
        )
        .route(
            "/api/providers/auth/import/candidates",
            get(list_provider_auth_import_candidates),
        )
        .route(
            "/api/providers/auth/import/profiles",
            get(list_provider_auth_import_profiles),
        )
        .route(
            "/api/providers/auth/import",
            post(import_provider_auth_candidates),
        )
        .route(
            "/api/providers/codex-crp/accounts",
            get(list_codex_accounts),
        )
        .route("/api/providers/codex/accounts", get(list_codex_accounts))
        .route(
            "/api/providers/codex-crp/import/host",
            get(probe_host_codex_import).post(import_host_codex_auth),
        )
        .route(
            "/api/providers/codex/import/host",
            get(probe_host_codex_import).post(import_host_codex_auth),
        )
        .route(
            "/api/providers/codex-crp/accounts/usage",
            get(get_codex_accounts_usage),
        )
        .route(
            "/api/providers/codex/accounts/usage",
            get(get_codex_accounts_usage),
        )
        .route(
            "/api/providers/codex-crp/accounts/login/start",
            post(start_codex_login),
        )
        .route(
            "/api/providers/codex/accounts/login/start",
            post(start_codex_login),
        )
        .route(
            "/api/providers/codex-crp/accounts/login/:id",
            get(get_codex_login).post(complete_codex_login),
        )
        .route(
            "/api/providers/codex/accounts/login/:id",
            get(get_codex_login).post(complete_codex_login),
        )
        .route(
            "/api/providers/codex-crp/active-account",
            put(set_codex_active_account),
        )
        .route(
            "/api/providers/codex/active-account",
            put(set_codex_active_account),
        )
        .route(
            "/api/providers/codex-crp/accounts/:id",
            delete(delete_codex_account),
        )
        .route(
            "/api/providers/codex/accounts/:id",
            delete(delete_codex_account),
        )
        .route(
            "/api/providers/claude-crp/accounts",
            get(list_claude_accounts).post(upsert_claude_account),
        )
        .route(
            "/api/providers/claude-crp/accounts/login/start",
            post(start_claude_login),
        )
        .route(
            "/api/providers/claude-crp/accounts/login/:id",
            get(get_claude_login),
        )
        .route(
            "/api/providers/claude-crp/active-account",
            put(set_claude_active_account),
        )
        .route(
            "/api/providers/claude-crp/accounts/:id",
            delete(delete_claude_account),
        )
        .route(
            "/api/providers/gemini/accounts",
            get(list_gemini_accounts).post(upsert_gemini_account),
        )
        .route(
            "/api/providers/gemini/accounts/login/start",
            post(start_gemini_login),
        )
        .route(
            "/api/providers/gemini/accounts/login/:id",
            get(get_gemini_login),
        )
        .route(
            "/api/providers/gemini/active-account",
            put(set_gemini_active_account),
        )
        .route(
            "/api/providers/gemini/accounts/:id",
            delete(delete_gemini_account),
        )
        .route(
            "/api/providers/qwen/accounts",
            get(list_qwen_accounts).post(upsert_qwen_account),
        )
        .route(
            "/api/providers/qwen/accounts/login/start",
            post(start_qwen_login),
        )
        .route(
            "/api/providers/qwen/accounts/login/:id",
            get(get_qwen_login),
        )
        .route(
            "/api/providers/qwen/active-account",
            put(set_qwen_active_account),
        )
        .route(
            "/api/providers/qwen/accounts/:id",
            delete(delete_qwen_account),
        )
        .route(
            "/api/providers/kimi/accounts/login/start",
            post(start_kimi_login),
        )
        .route(
            "/api/providers/kimi/accounts/login/:id",
            get(get_kimi_login),
        )
        .route(
            "/api/providers/kimi/accounts",
            get(list_kimi_accounts).post(upsert_kimi_account),
        )
        .route(
            "/api/providers/kimi/active-account",
            put(set_kimi_active_account),
        )
        .route(
            "/api/providers/kimi/accounts/:id",
            delete(delete_kimi_account),
        )
        .route(
            "/api/providers/amp/accounts/login/start",
            post(start_amp_login),
        )
        .route("/api/providers/amp/accounts/login/:id", get(get_amp_login))
        .route(
            "/api/providers/amp/accounts",
            get(list_amp_accounts).post(upsert_amp_account),
        )
        .route(
            "/api/providers/amp/active-account",
            put(set_amp_active_account),
        )
        .route(
            "/api/providers/amp/accounts/:id",
            delete(delete_amp_account),
        )
        .route(
            "/api/providers/mistral/accounts",
            get(list_mistral_accounts).post(upsert_mistral_account),
        )
        .route(
            "/api/providers/mistral/accounts/login/start",
            post(start_mistral_login),
        )
        .route(
            "/api/providers/mistral/accounts/login/:id",
            get(get_mistral_login),
        )
        .route(
            "/api/providers/mistral/active-account",
            put(set_mistral_active_account),
        )
        .route(
            "/api/providers/mistral/accounts/:id",
            delete(delete_mistral_account),
        )
        .route(
            "/api/providers/copilot/accounts",
            get(list_copilot_accounts).post(upsert_copilot_account),
        )
        .route(
            "/api/providers/copilot/active-account",
            put(set_copilot_active_account),
        )
        .route(
            "/api/providers/copilot/accounts/:id",
            delete(delete_copilot_account),
        )
        .route(
            "/api/providers/cursor/accounts",
            get(list_cursor_accounts).post(upsert_cursor_account),
        )
        .route(
            "/api/providers/cursor/accounts/login/start",
            post(start_cursor_login),
        )
        .route(
            "/api/providers/cursor/accounts/login/:id",
            get(get_cursor_login),
        )
        .route(
            "/api/providers/cursor/active-account",
            put(set_cursor_active_account),
        )
        .route(
            "/api/providers/cursor/accounts/:id",
            delete(delete_cursor_account),
        )
        .route(
            "/api/providers/:id/install",
            post(provider_launch::install_provider),
        )
        .route(
            "/api/providers/install/:install_id",
            get(provider_launch::get_install),
        )
        .route(
            "/api/providers/install/statuses",
            post(provider_launch::get_install_statuses),
        )
        .route(
            "/api/providers/install/:install_id/cancel",
            post(provider_launch::cancel_install),
        )
        .route(
            "/api/providers/install/:install_id/events",
            get(provider_launch::list_install_events),
        )
        .route(
            "/api/providers/install/:install_id/stream",
            get(provider_launch::install_stream_sse),
        )
}
