name = "ctx-turbo-cache"
main = "./src/worker.mjs"
compatibility_date = "2026-04-08"

[[r2_buckets]]
binding = "CACHE_BUCKET"
bucket_name = "example-build-cache"
preview_bucket_name = "example-build-cache"

[vars]
CACHE_OBJECT_PREFIX = "turbo"
EVENTS_OBJECT_PREFIX = "turbo-events"
