const fs = require("node:fs");
const path = require("node:path");

const {
  CTX_HTTP_SHARED_SOURCE_GLOBS,
  CTX_HTTP_SUITES,
  validateCtxHttpSuites,
} = require("../ctx_http_suites.cjs");
const {
  REPO_RUST_BUILD_GRAPH_INPUT_PREFIXES,
  REPO_RUST_BUILD_GRAPH_INPUTS,
  ROOT_RUST_INPUTS,
  buildWorkspaceGraph,
  getGateManagedCrates,
} = require("../rust_workspace_graph.cjs");
const {
  BAZEL_TEST_CRATES,
  SERIAL_CARGO_TEST_CRATES,
} = require("../rust_gate_plan.cjs");
const { FAMILIES, getFamiliesById } = require("./families.cjs");
const { sortEntries, validateEntry } = require("./schema.cjs");
const { buildWebE2EExecutionTarget } = require("./web_e2e_runtime_profiles.cjs");

const repoRoot = path.resolve(__dirname, "..", "..", "..", "..");
const coreRoot = path.join(repoRoot, "core");
const rustWorkspaceGraph = buildWorkspaceGraph(coreRoot);
const packageJsonPath = path.join(coreRoot, "package.json");
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
const providerMatrixPath = path.join(coreRoot, "apps", "desktop", "automation", "fixtures", "provider_auth_matrix.json");
const providerMatrix = JSON.parse(fs.readFileSync(providerMatrixPath, "utf8"));
const harnessInstallMatrixPath = path.join(coreRoot, "apps", "desktop", "automation", "fixtures", "harness_install_matrix.json");
const harnessInstallMatrix = JSON.parse(fs.readFileSync(harnessInstallMatrixPath, "utf8"));
const webRoot = path.join(coreRoot, "apps", "web");
const webE2ERoot = path.join(webRoot, "e2e");
const webSuiteRoot = path.join(webE2ERoot, "suites");
const webSuites = ["premerge_required", "release_required", "cross_platform", "visual", "soak", "load"];
const RELEASE_RELEVANT_GLOBS = [
  ".buildkite/pipelines/release.yml",
  "core/apps/desktop/**",
  "core/crates/ctx-http/**",
  "core/scripts/desktop_check_versions.cjs",
  "core/scripts/desktop_set_version.cjs",
  "core/scripts/desktop_version.cjs",
  "core/scripts/release_version.cjs",
  "scripts/buildbuddy/run_release*.sh",
  "scripts/release_*.sh",
  "tools/bazel/**",
];
const RELEASE_CONTRACT_RELEVANT_GLOBS = [
  ".buildkite/pipelines/main.yml",
  ".buildkite/pipelines/release.yml",
  "core/apps/desktop/**",
  "core/scripts/desktop_check_versions.cjs",
  "core/scripts/desktop_set_version.cjs",
  "core/scripts/desktop_version.cjs",
  "core/scripts/release_version.cjs",
  "core/scripts/runtime_lock_*.cjs",
  "scripts/buildbuddy/run_release*.sh",
  "scripts/release_*.sh",
  "tools/bazel/**",
];
const PROVIDER_AUTH_VALIDATE_GLOBS = [
  ".buildkite/**",
  "buildbuddy.yaml",
  "core/apps/web/src/**",
  "core/apps/desktop/automation/**",
  "core/apps/desktop/scripts/run_provider_auth_matrix.sh",
  "core/crates/ctx-http/src/api/auth/browser.rs",
  "core/package.json",
  "core/scripts/desktop_e2e_preflight.cjs",
  "core/scripts/desktop_e2e_secret_contract.cjs",
  "core/scripts/desktop_e2e_secret_contract_lib.cjs",
  "core/scripts/desktop_browser_route_contract.cjs",
  "core/scripts/desktop_browser_route_contract.test.cjs",
  "core/scripts/validate_provider_auth_matrix.cjs",
  "core/scripts/validate_provider_auth_matrix.test.cjs",
  "scripts/buildbuddy/run_provider_auth_matrix.sh",
];
const HARNESS_INSTALL_MATRIX_GLOBS = [
  ".buildkite/**",
  "buildbuddy.yaml",
  "core/apps/desktop/automation/fixtures/harness_install_matrix.json",
  "core/apps/desktop/automation/docs/harness_install_matrix.md",
  "core/apps/desktop/scripts/run_harness_install_matrix.sh",
  "core/apps/desktop/scripts/run_harness_install_matrix.test.cjs",
  "core/package.json",
  "core/scripts/harness_install_matrix_validate_bazel.cjs",
  "core/scripts/release_runtime_install_smoke_contract.test.cjs",
  "core/scripts/validate_harness_install_matrix.cjs",
  "core/scripts/validate_harness_install_matrix.test.cjs",
  "scripts/buildkite/run_harness_install_matrix_macos.sh",
  "scripts/release_runtime_install_smoke.sh",
  "scripts/tests/updater_linux_release_truth.sh",
];
const INSTALL_BOOTSTRAP_GLOBS = [
  ".buildkite/**",
  "buildbuddy.yaml",
  "install-site/**",
  "scripts/buildbuddy/run_install_bootstrap_contracts.sh",
];
const PRETEXT_MEASUREMENT_CODE_GLOBS = [
  "core/apps/web/e2e/utils/pretextWrapRuleFuzz.ts",
  "core/apps/web/scripts/pretext-parity-probe*",
  "core/apps/web/src/pages/SessionPage.markdown*",
  "core/apps/web/src/pages/SessionThreadMessageList.pretextVirtualizer*",
  "core/apps/web/src/pages/usePretextVirtualizerSessionController*",
  "core/apps/web/src/pages/sessionThread/*Pretext*",
  "core/apps/web/src/pages/sessionThread/pretext*",
  "core/apps/web/src/pages/sessionThread/sessionMarkdown*",
  "core/apps/web/src/pages/sessionThread/sessionPlainTextMeasurement*",
  "core/apps/web/src/pages/sessionThread/sessionTextMeasurement*",
  "core/apps/web/src/pages/sessionThread/sessionThreadLayoutTokens*",
  "core/apps/web/src/pages/sessionThread/sessionThreadMeasurementContract*",
  "core/apps/web/src/pages/sessionThread/transcript*",
  "core/apps/web/src/pages/sessionView/SessionPage.markdown*",
  "core/apps/web/src/testdata/pretext*",
  "core/apps/web/src/utils/inlineCodeFragments*",
];
const PRETEXT_MEASUREMENT_SOURCE_GLOBS = [
  ...PRETEXT_MEASUREMENT_CODE_GLOBS,
  ".ctx/docs/pretext_wrap_rule_catalog.md",
  ".ctx/docs/workbench_pretext_parity_debugging.md",
  "core/apps/web/BUILD.bazel",
  "core/apps/web/package.json",
  "core/package.json",
];
const RUST_ROOT_SOURCE_GLOBS = [
  ...ROOT_RUST_INPUTS.map((input) => `core/${input}`),
  ...REPO_RUST_BUILD_GRAPH_INPUTS,
  ...REPO_RUST_BUILD_GRAPH_INPUT_PREFIXES.map((prefix) => `${prefix}**`),
];
const RUST_FAMILY_BY_CRATE = {
  "codex-crp": "artifacts-provenance",
  "ctx-avf-linux-guest-agent": "sandbox-runtime",
  "ctx-avf-linux-runtime": "sandbox-runtime",
  "ctx-bundled-assets": "artifacts-provenance",
  "ctx-client": "web-workbench",
  "ctx-core": "build-graph",
  "ctx-crp-protocol": "provider-runtime",
  "ctx-desktop-ipc": "desktop-shell",
  "ctx-docs-mirror": "attachments-artifacts",
  "ctx-egress-proxy": "sandbox-runtime",
  "ctx-events": "workspace-stream",
  "ctx-execution-runtime": "sandbox-runtime",
  "ctx-fs": "repo-vcs",
  "ctx-harness-runtime": "sandbox-runtime",
  "ctx-harness-setup": "toolchain-bootstrap",
  "ctx-harness-sources": "toolchain-bootstrap",
  "ctx-linux-sandbox-runtime": "sandbox-runtime",
  "ctx-llm-relay-authority": "provider-runtime",
  "ctx-llm-relay-contract": "provider-runtime",
  "ctx-load-test": "resilience-performance",
  "ctx-managed-installs": "distribution-install",
  "ctx-mcp": "subagents-orchestration",
  "ctx-merge-queue": "repo-vcs",
  "ctx-provider-accounts": "provider-auth",
  "ctx-provider-auth-import": "provider-auth",
  "ctx-provider-install": "provider-auth",
  "ctx-provider-matrix": "provider-auth",
  "ctx-provider-runtime": "provider-runtime",
  "ctx-providers": "provider-runtime",
  "ctx-runtime-assets": "distribution-install",
  "ctx-sandbox-container-runtime": "sandbox-runtime",
  "ctx-sandbox-contract": "sandbox-runtime",
  "ctx-sandbox-materialization": "sandbox-runtime",
  "ctx-session-tools": "turns-terminal",
  "ctx-storage-admission": "workspace-stream",
  "ctx-store": "workspace-stream",
  "ctx-transport-runtime": "subagents-orchestration",
  "ctx-tunnel-control-plane": "subagents-orchestration",
  "ctx-tunnel-relay": "subagents-orchestration",
  "ctx-tunnel-router": "subagents-orchestration",
  "ctx-tunnel-store": "subagents-orchestration",
  "ctx-workspace-active-snapshot": "workspace-stream",
  "ctx-workspace-config": "settings-config",
  "ctx-workspace-container": "workspace-stream",
  "ctx-workspace-runtime": "workspace-stream",
  "ctx-workspace-services": "workspace-stream",
  "ctx-worktree-data-plane": "repo-vcs",
};

function toPosix(value) {
  return value.split(path.sep).join("/");
}

function relativeToRepo(absPath) {
  return toPosix(path.relative(repoRoot, absPath));
}

function normalizeManifestSpec(line) {
  const cleaned = String(line || "").trim();
  if (!cleaned || cleaned.startsWith("#")) {
    return null;
  }
  return cleaned.startsWith("e2e/") ? cleaned : `e2e/${cleaned}`;
}

function readWebSuiteMap() {
  const map = new Map();
  for (const suite of webSuites) {
    const manifestPath = path.join(webSuiteRoot, `${suite}.txt`);
    const specs = [...new Set(fs
      .readFileSync(manifestPath, "utf8")
      .split(/\r?\n/u)
      .map(normalizeManifestSpec)
      .filter(Boolean)
    )].sort();
    map.set(suite, specs);
  }
  return map;
}

function classifyWebSpecFamily(specPath) {
  const base = path.basename(specPath);
  if (/attachment/u.test(base)) {
    return "attachments-artifacts";
  }
  if (/update|updater/u.test(base)) {
    return "updates-release";
  }
  if (/desktop|webview/u.test(base)) {
    return "desktop-shell";
  }
  if (/settings/u.test(base)) {
    return "settings-config";
  }
  if (/provider/u.test(base)) {
    return "provider-runtime";
  }
  if (/terminal/u.test(base)) {
    return "turns-terminal";
  }
  if (/ws-|snapshot|stream|session-gap/u.test(base)) {
    return "workspace-stream";
  }
  return "web-workbench";
}

function buildCtxHttpEntries() {
  const entries = [];
  for (const suite of CTX_HTTP_SUITES) {
    const familyBySuite = {
      base: "build-graph",
      "workspace-stream": "workspace-stream",
      "provider-auth": "provider-auth",
      "provider-runtime-simulated": "provider-runtime",
      "provider-runtime-live": "provider-runtime",
      "repo-vcs": "repo-vcs",
      "scheduler-runtime": "turns-terminal",
      "turns-terminal": "turns-terminal",
      "attachments-routing": "attachments-artifacts",
      "subagents-control": "subagents-orchestration",
      "subagents-local-runtime": "subagents-orchestration",
      "updates-release": "updates-release",
      "sandbox-runtime-simulated": "sandbox-runtime",
      "sandbox-runtime-container-e2e": "sandbox-runtime",
      "sandbox-runtime-resource-governance": "sandbox-runtime",
      "sandbox-runtime-memory-leak": "sandbox-runtime",
    };
    const worldBySuite = {
      base: "hermetic",
      "workspace-stream": "simulated",
      "provider-auth": "fake-provider",
      "provider-runtime-simulated": "simulated",
      "provider-runtime-live": "external-service",
      "repo-vcs": "simulated",
      "scheduler-runtime": "simulated",
      "turns-terminal": "simulated",
      "attachments-routing": "simulated",
      "subagents-control": "simulated",
      "subagents-local-runtime": "external-service",
      "updates-release": "simulated",
      "sandbox-runtime-simulated": "simulated",
      "sandbox-runtime-container-e2e": "external-service",
      "sandbox-runtime-resource-governance": "external-service",
      "sandbox-runtime-memory-leak": "external-service",
    };
    const surfaceBySuite = {
      base: "compile",
      "provider-runtime-live": "system",
      "subagents-local-runtime": "system",
      "sandbox-runtime-container-e2e": "system",
      "sandbox-runtime-resource-governance": "resilience",
      "sandbox-runtime-memory-leak": "performance",
    };
    const oracleBySuite = {
      base: "compiler",
      "provider-runtime-live": "golden-flow",
      "subagents-local-runtime": "golden-flow",
      "sandbox-runtime-container-e2e": "golden-flow",
      "sandbox-runtime-memory-leak": "budget",
    };
    const costBySuite = {
      base: "fast",
      "provider-runtime-live": "slow",
      "subagents-local-runtime": "slow",
      "sandbox-runtime-container-e2e": "medium",
      "sandbox-runtime-resource-governance": "medium",
      "sandbox-runtime-memory-leak": "soak",
    };
    const requirementsBySuite = {
      base: ["linux", "buildbuddy-rbe"],
      "workspace-stream": ["linux", "buildbuddy-rbe"],
      "provider-auth": ["linux", "buildbuddy-rbe"],
      "provider-runtime-simulated": ["linux", "buildbuddy-rbe"],
      "provider-runtime-live": ["linux", "buildbuddy-rbe", "network"],
      "repo-vcs": ["linux", "buildbuddy-rbe"],
      "scheduler-runtime": ["linux", "buildbuddy-rbe"],
      "turns-terminal": ["linux", "buildbuddy-rbe"],
      "attachments-routing": ["linux", "buildbuddy-rbe"],
      "subagents-control": ["linux", "buildbuddy-rbe"],
      "subagents-local-runtime": ["linux", "buildbuddy-rbe", "network"],
      "updates-release": ["linux", "buildbuddy-rbe"],
      "sandbox-runtime-simulated": ["linux", "buildbuddy-rbe"],
      "sandbox-runtime-container-e2e": ["linux", "buildbuddy-rbe", "docker", "network"],
      "sandbox-runtime-resource-governance": ["linux", "buildbuddy-rbe"],
      "sandbox-runtime-memory-leak": ["linux", "buildbuddy-rbe", "long-running"],
    };
    const stabilityBySuite = {
      base: "stable",
      "workspace-stream": "stable",
      "provider-auth": "stable",
      "provider-runtime-simulated": "stable",
      "provider-runtime-live": "quarantined",
      "repo-vcs": "stable",
      "scheduler-runtime": "stable",
      "turns-terminal": "stable",
      "attachments-routing": "stable",
      "subagents-control": "stable",
      "subagents-local-runtime": "quarantined",
      "updates-release": "stable",
      "sandbox-runtime-simulated": "stable",
      "sandbox-runtime-container-e2e": "quarantined",
      "sandbox-runtime-resource-governance": "quarantined",
      "sandbox-runtime-memory-leak": "quarantined",
    };
    const executionBySuite = {
      base: "bazel-rbe-preferred",
      "workspace-stream": "bazel-rbe-preferred",
      "provider-auth": "bazel-rbe-preferred",
      "provider-runtime-simulated": "bazel-rbe-preferred",
      "provider-runtime-live": "bazel-addressable",
      "repo-vcs": "bazel-rbe-preferred",
      "scheduler-runtime": "bazel-rbe-preferred",
      "turns-terminal": "bazel-rbe-preferred",
      "attachments-routing": "bazel-rbe-preferred",
      "subagents-control": "bazel-rbe-preferred",
      "subagents-local-runtime": "bazel-addressable",
      "updates-release": "bazel-addressable",
      "sandbox-runtime-simulated": "bazel-rbe-preferred",
      "sandbox-runtime-container-e2e": "bazel-addressable",
      "sandbox-runtime-resource-governance": "bazel-addressable",
      "sandbox-runtime-memory-leak": "bazel-addressable",
    };
    const world = suite.world || worldBySuite[suite.name];
    const entry = {
      id: `ctx-http.${suite.name}`,
      title: `ctx-http: ${suite.name}`,
      family: suite.family || familyBySuite[suite.name],
      entrypointType: "ctx-http-suite",
      entrypoint: suite.name,
      surface: suite.surface || surfaceBySuite[suite.name] || (suite.type === "base" ? "compile" : "integration"),
      oracle: suite.oracle || oracleBySuite[suite.name] || (suite.type === "base" ? "compiler" : "direct-assertion"),
      world,
      cost: suite.cost || costBySuite[suite.name] || (suite.type === "base" ? "fast" : "fast"),
      requirements: suite.requirements || requirementsBySuite[suite.name] || ["linux", "buildbuddy-rbe"],
      stability: suite.stability || stabilityBySuite[suite.name] || (world === "external-service" ? "quarantined" : "stable"),
      execution: suite.execution || executionBySuite[suite.name],
      owner: "ctx-http",
      sourceGlobs: [
        "core/scripts/ctx_http_suite_task.cjs",
        "core/scripts/lib/ctx_http_suites.cjs",
        ...(suite.type === "integration" ? CTX_HTTP_SHARED_SOURCE_GLOBS.map((glob) => `core/${glob}`) : []),
        ...suite.sourceGlobs.map((glob) => `core/${glob}`),
        ...suite.testFiles.map((testFile) => `core/crates/ctx-http/tests/${testFile}.rs`),
      ],
      dependencyCrates: suite.dependencyCrates,
      notes: suite.description,
      exception: "",
    };
    entries.push(entry);
  }
  return entries;
}

function buildWebE2EEntries() {
  const suiteMap = readWebSuiteMap();
  const entries = [];
  const suiteMetadata = {
    premerge_required: {
      cost: "fast",
      stability: "stable",
      world: "simulated",
      execution: "bazel-addressable",
    },
    release_required: {
      cost: "medium",
      stability: "stable",
      world: "local-packaged-artifact",
      execution: "bazel-addressable",
    },
    cross_platform: {
      cost: "medium",
      stability: "stable",
      world: "simulated",
      execution: "bazel-addressable",
    },
    visual: {
      cost: "slow",
      stability: "quarantined",
      world: "simulated",
      execution: "bazel-addressable",
    },
    soak: {
      cost: "soak",
      stability: "quarantined",
      world: "simulated",
      execution: "bazel-addressable",
    },
    load: {
      cost: "slow",
      stability: "stable",
      world: "simulated",
      execution: "bazel-addressable",
    },
  };

  for (const [suite, specs] of suiteMap.entries()) {
    for (const spec of specs) {
      const meta = suiteMetadata[suite];
      const family = classifyWebSpecFamily(spec);
      entries.push({
        id: `web-e2e.${spec.replace(/^e2e\//u, "").replace(/\.spec\.ts$/u, "").replace(/[/.]/gu, "-")}`,
        title: `web-e2e: ${path.basename(spec)}`,
        family,
        entrypointType: "web-e2e-spec",
        entrypoint: `core/apps/web/${spec}`,
        suite,
        surface: "system",
        oracle: "golden-flow",
        world: meta.world,
        cost: meta.cost,
        requirements: ["linux", "browser"],
        stability: meta.stability,
        execution: meta.execution,
        owner: "web-workbench",
        sourceGlobs: [`core/apps/web/${spec}`],
        dependencyCrates: [],
        executionTargets: {
          webE2E: buildWebE2EExecutionTarget({ spec, family, suite }),
        },
        notes: `Primary suite: ${suite}`,
        exception: "",
      });
    }
  }

  return entries;
}

function buildProviderMatrixEntries() {
  const cells = Array.isArray(providerMatrix.cells) ? providerMatrix.cells : [];
  const requiredCount = cells.filter((cell) => cell.lane === "required" && cell.support === "supported").length;
  const nightlyCells = cells.filter((cell) => cell.lane === "nightly" && cell.support === "supported");
  const nightlyAuthModeCount = (authMode) => nightlyCells.filter((cell) => cell.auth_mode === authMode).length;
  return [
    {
      id: "provider-auth-matrix.required",
      title: "Provider auth matrix (required lane)",
      family: "provider-auth",
      entrypointType: "provider-matrix-lane",
      entrypoint: "core/apps/desktop/automation/fixtures/provider_auth_matrix.json#required",
      surface: "system",
      oracle: "golden-flow",
      world: "fake-provider",
      cost: "medium",
      requirements: ["mac", "browser", "network", "single-mac"],
      stability: "stable",
      execution: "script-local",
      owner: "provider-auth",
      sourceGlobs: [
        "core/apps/desktop/automation/fixtures/provider_auth_matrix.json",
        "core/apps/desktop/scripts/run_provider_auth_matrix.sh",
      ],
      dependencyCrates: [],
      notes: `${requiredCount} supported required cells currently live in the matrix.`,
      exception: "Intentional fake-provider desktop matrix truth on the shared Mac/browser host; orchestration remains script-local by design.",
    },
    {
      id: "provider-auth-matrix.nightly.endpoint-write",
      title: "Provider auth matrix (nightly endpoint-write slice)",
      family: "provider-auth",
      entrypointType: "core-package-script",
      entrypoint: "verify:desktop:provider-auth-matrix:endpoint-write",
      surface: "system",
      oracle: "golden-flow",
      world: "live-provider",
      cost: "slow",
      requirements: ["mac", "browser", "network", "single-mac", "long-running"],
      stability: "quarantined",
      execution: "script-local",
      owner: "provider-auth",
      sourceGlobs: [
        "core/apps/desktop/automation/fixtures/provider_auth_matrix.json",
        "core/apps/desktop/scripts/run_provider_auth_matrix.sh",
      ],
      dependencyCrates: [],
      notes: `${nightlyAuthModeCount("endpoint_api_key")} supported nightly endpoint-write cells currently live in the matrix.`,
      exception: "Intentional live-provider nightly matrix slice on the shared Mac/browser host; keep script-local and quarantined.",
    },
    {
      id: "provider-auth-matrix.nightly.subscription-oauth",
      title: "Provider auth matrix (nightly subscription-oauth slice)",
      family: "provider-auth",
      entrypointType: "core-package-script",
      entrypoint: "verify:desktop:provider-auth-matrix:oauth-subscription",
      surface: "system",
      oracle: "golden-flow",
      world: "live-provider",
      cost: "slow",
      requirements: ["mac", "browser", "network", "single-mac", "long-running"],
      stability: "quarantined",
      execution: "script-local",
      owner: "provider-auth",
      sourceGlobs: [
        "core/apps/desktop/automation/fixtures/provider_auth_matrix.json",
        "core/apps/desktop/scripts/run_provider_auth_matrix.sh",
      ],
      dependencyCrates: [],
      notes: `${nightlyAuthModeCount("subscription_oauth")} supported nightly subscription-oauth cells currently live in the matrix.`,
      exception: "Intentional live-provider nightly matrix slice on the shared Mac/browser host; keep script-local and quarantined.",
    },
    {
      id: "provider-auth-matrix.nightly.auth-import",
      title: "Provider auth matrix (nightly auth-import slice)",
      family: "provider-auth",
      entrypointType: "core-package-script",
      entrypoint: "verify:desktop:provider-auth-matrix:auth-import",
      surface: "system",
      oracle: "golden-flow",
      world: "live-provider",
      cost: "slow",
      requirements: ["mac", "browser", "network", "single-mac", "long-running"],
      stability: "quarantined",
      execution: "script-local",
      owner: "provider-auth",
      sourceGlobs: [
        "core/apps/desktop/automation/fixtures/provider_auth_matrix.json",
        "core/apps/desktop/scripts/run_provider_auth_matrix.sh",
      ],
      dependencyCrates: [],
      notes: `${nightlyAuthModeCount("auth_import")} supported nightly auth-import cells currently live in the matrix.`,
      exception: "Intentional live-provider nightly matrix slice on the shared Mac/browser host; keep script-local and quarantined.",
    },
  ];
}

function countHarnessInstallCellsForLane(lane) {
  let count = 0;
  for (const provider of Array.isArray(harnessInstallMatrix.providers) ? harnessInstallMatrix.providers : []) {
    for (const cell of Object.values(provider.cells || {})) {
      const lanes = Array.isArray(cell.lanes) ? cell.lanes : [];
      if (cell.support === "supported" && lanes.includes(lane)) count += 1;
    }
  }
  return count;
}

function buildHarnessInstallMatrixEntries() {
  const releaseCount = countHarnessInstallCellsForLane("release");
  const previewCount = countHarnessInstallCellsForLane("preview");
  const nightlyCount = countHarnessInstallCellsForLane("nightly");
  return [
    {
      id: "distribution-install.harness-install-matrix-validate",
      title: "Harness install matrix validation",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "bazel:harness-install-matrix:validate",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "distribution",
      sourceGlobs: HARNESS_INSTALL_MATRIX_GLOBS,
      dependencyCrates: [],
      notes: "Static contract proving every installable harness provider has macOS/Linux host/sandbox matrix coverage.",
      exception: "",
    },
    {
      id: "distribution-install.harness-install-matrix-preview-macos",
      title: "Harness install matrix preview macOS",
      family: "distribution-install",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_harness_install_matrix_macos.sh",
      surface: "artifact",
      oracle: "golden-flow",
      world: "local-packaged-artifact",
      cost: "slow",
      requirements: ["mac", "network", "single-mac", "long-running"],
      stability: "stable",
      execution: "script-local",
      owner: "distribution",
      sourceGlobs: HARNESS_INSTALL_MATRIX_GLOBS,
      dependencyCrates: [],
      notes: `${previewCount} preview cells install all managed harness providers from the produced macOS preview app.`,
      exception: "Intentional packaged-app install truth on the shared Mac; this consumes signed app artifacts and live provider downloads, so it is not Bazel-addressable.",
    },
    {
      id: "distribution-install.harness-install-matrix-release",
      title: "Harness install matrix release proof",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "verify:desktop:harness-install-matrix:release",
      surface: "system",
      oracle: "golden-flow",
      world: "local-packaged-artifact",
      cost: "slow",
      requirements: ["mac", "linux", "network", "single-mac", "long-running"],
      stability: "stable",
      execution: "script-local",
      owner: "distribution",
      sourceGlobs: HARNESS_INSTALL_MATRIX_GLOBS,
      dependencyCrates: [],
      notes: `${releaseCount} release cells are required across macOS/Linux and host/sandbox before stable promotion. Linux release proof is executed by updater_linux_release_truth; macOS proof is an explicit release pipeline step.`,
      exception: "Intentional packaged-app install truth on real OS workers; Buildkite supplies exact app and daemon artifacts.",
    },
    {
      id: "distribution-install.harness-install-matrix-nightly",
      title: "Harness install matrix nightly",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "verify:desktop:harness-install-matrix:nightly",
      surface: "system",
      oracle: "golden-flow",
      world: "live-provider",
      cost: "slow",
      requirements: ["mac", "linux", "network", "single-mac", "long-running"],
      stability: "quarantined",
      execution: "script-local",
      owner: "distribution",
      sourceGlobs: HARNESS_INSTALL_MATRIX_GLOBS,
      dependencyCrates: [],
      notes: `${nightlyCount} nightly cells repeat installability and are the expansion point for launch/probe/first-turn breadth.`,
      exception: "Intentional live-provider breadth outside the default nightly union until queue capacity and app-artifact source are explicit.",
    },
  ];
}

function buildRustEntries() {
  const crates = getGateManagedCrates(rustWorkspaceGraph).filter((crate) => crate.crateName !== "ctx-http");
  const rustGateCrates = crates.map((crate) => crate.crateName);
  const entries = [
    {
      id: "build-graph.rust-package-scripts-check",
      title: "Rust package scripts check",
      family: "build-graph",
      entrypointType: "core-package-script",
      entrypoint: "rust:package-scripts:check",
      surface: "compile",
      oracle: "compiler",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "script-local",
      owner: "rust-workspace",
      sourceGlobs: RUST_ROOT_SOURCE_GLOBS,
      dependencyCrates: rustGateCrates,
      notes: "Generated Rust package-script freshness preflight for non-ctx-http workspace crates.",
      exception: "Intentional host-local Rust workspace preflight until a measured wall-clock bottleneck justifies deeper Bazel decomposition.",
    },
    {
      id: "build-graph.rust-bazel-deps-check",
      title: "Rust Bazel deps generated config check",
      family: "build-graph",
      entrypointType: "core-package-script",
      entrypoint: "rust:bazel-deps:check",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux"],
      stability: "stable",
      execution: "script-local",
      owner: "rust-workspace",
      sourceGlobs: [
        ...RUST_ROOT_SOURCE_GLOBS,
        "core/scripts/rust_bazel_deps_contract.sh",
      ],
      dependencyCrates: [],
      notes: "Freshness check for generated Bazel Rust dependency metadata and root Bazel graph inputs.",
      exception: "Intentional script-local generated-deps guard until the Rust deps generator is Bazel-addressable.",
    },
  ];

  for (const crate of crates) {
    const family = RUST_FAMILY_BY_CRATE[crate.crateName];
    if (!family) {
      throw new Error(`missing taxonomy family mapping for Rust crate: ${crate.crateName}`);
    }
    const strategyNotes = [];
    if (BAZEL_TEST_CRATES.has(crate.crateName)) {
      strategyNotes.push("Bazel-covered Rust gate");
    } else if (SERIAL_CARGO_TEST_CRATES.has(crate.crateName)) {
      strategyNotes.push("Serial cargo-test Rust gate");
    } else {
      strategyNotes.push("Nextest-backed Rust gate");
    }
    entries.push({
      id: `${family}.rust-gate.${crate.crateName}`,
      title: `Rust gate: ${crate.crateName}`,
      family,
      entrypointType: "rust-crate-gate",
      entrypoint: crate.crateName,
      surface: "integration",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: BAZEL_TEST_CRATES.has(crate.crateName) ? "bazel-rbe-preferred" : "script-local",
      owner: "rust-workspace",
      sourceGlobs: [`core/${crate.relDir}/**`],
      dependencyCrates: [crate.crateName],
      notes: strategyNotes.join(". "),
      exception: "",
    });
  }

  return entries;
}

function buildStaticEntries() {
  return [
    {
      id: "repo-contracts.source-file-size",
      title: "Source file size guard",
      family: "repo-contracts",
      entrypointType: "core-package-script",
      entrypoint: "source:file-size:report",
      surface: "contract",
      oracle: "budget",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux"],
      stability: "stable",
      execution: "script-local",
      owner: "repo-contracts",
      sourceGlobs: [
        "core/scripts/source_file_size_guard.cjs",
        "core/apps/web/src/**",
        "core/apps/desktop/src-tauri/src/**",
        "core/crates/*/src/**",
        "core/packages/*/src/**",
        "core/tools/*/src/**",
      ],
      dependencyCrates: [],
      notes: "Repository size-budget audit for production source files. The enforce variant is reserved for the follow-up cleanup once the current oversized-file baseline is refactored.",
      exception: "Intentional script-local budget report until the existing oversized-file baseline is removed and the enforce variant can be made promotion-blocking again.",
    },
    {
      id: "repo-contracts.testing-taxonomy-check",
      title: "Testing taxonomy generated docs freshness",
      family: "repo-contracts",
      entrypointType: "core-package-script",
      entrypoint: "testing:taxonomy:check",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux"],
      stability: "stable",
      execution: "script-local",
      owner: "repo-contracts",
      sourceGlobs: [
        "core/scripts/generate_test_taxonomy_docs.cjs",
        "core/scripts/test_taxonomy_execution_contract.test.cjs",
        "core/scripts/verification_router_contract.test.cjs",
        "core/scripts/lib/test_taxonomy/**",
        ".ctx/docs/testing_taxonomy.md",
        ".ctx/docs/testing_exceptions.generated.md",
        ".ctx/docs/testing_inventory.generated.md",
        ".ctx/docs/testing_profiles.generated.md",
      ],
      dependencyCrates: [],
      notes: "Generated taxonomy/profile documentation freshness check.",
      exception: "Intentional script-local generated-doc freshness guard until the generator is Bazel-addressable.",
    },
    {
      id: "repo-contracts.buildkite-pipeline",
      title: "Buildkite pipeline contracts",
      family: "repo-contracts",
      entrypointType: "core-package-script",
      entrypoint: "bazel:buildkite:pipeline:test",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "ci-release",
      sourceGlobs: [
        "core/scripts/buildkite_pipeline_contract.test.cjs",
        "core/scripts/lib/dev_promotion.cjs",
        "core/scripts/promote_dev_to_main.cjs",
        "core/scripts/promote_dev_to_main.test.cjs",
        "core/scripts/render_buildkite_checkin_gate.cjs",
        "core/scripts/trigger_buildkite_mac_nightly.cjs",
        "core/scripts/trigger_buildkite_mac_nightly.test.cjs",
        ".buildkite/**",
        "scripts/buildkite/**",
        "scripts/ci/**",
      ],
      dependencyCrates: [],
      notes: "Pipeline and orchestration contract coverage.",
      exception: "",
    },
    {
      id: "build-graph.release-bundle-contracts",
      title: "Release bundle Bazel contracts",
      family: "build-graph",
      entrypointType: "file",
      entrypoint: "core/scripts/release_bundle_contracts_bazel_contract.test.cjs",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "ci-release",
      sourceGlobs: [
        "core/scripts/release_bundle_contracts_bazel_contract.test.cjs",
        "core/tools/bazel/**",
      ],
      dependencyCrates: [],
      notes: "Bazel-side release bundle and artifact contract coverage.",
      exception: "",
    },
    {
      id: "build-graph.release-bundle-contracts-linux-x86_64",
      title: "Release bundle contracts (linux-x86_64)",
      family: "build-graph",
      entrypointType: "core-package-script",
      entrypoint: "release:bundle:contracts:linux-x86_64",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "ci-release",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/release_bundle_contracts_bazel_contract.test.cjs",
        ...RELEASE_CONTRACT_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Executable release bundle contract gate used by release preflight.",
      exception: "",
    },
    {
      id: "distribution-install.install-site-contracts",
      title: "Install-site Bazel contracts",
      family: "distribution-install",
      entrypointType: "file",
      entrypoint: "core/scripts/install_site_bazel_contract.test.cjs",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "distribution",
      sourceGlobs: [
        "core/scripts/install_site_bazel_contract.test.cjs",
        "install-site/**",
      ],
      dependencyCrates: [],
      notes: "Install-site contract coverage.",
      exception: "",
    },
    {
      id: "distribution-install.install-bootstrap-contracts",
      title: "Install bootstrap contracts",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "install:bootstrap:contracts",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: [],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "distribution",
      sourceGlobs: INSTALL_BOOTSTRAP_GLOBS,
      dependencyCrates: [],
      notes: "Bootstrap/install contract execution used by ctx-main linux and mac gate steps.",
      exception: "",
    },
    {
      id: "distribution-install.provider-matrix-archive-contracts",
      title: "Provider matrix archive contracts",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "bazel:desktop:provider-matrix:contracts",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "distribution",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/provider_matrix_archive_gap_report.test.cjs",
        "core/scripts/provider_matrix_required_targets_gate.test.cjs",
      ],
      dependencyCrates: [],
      notes: "Archive-target and runtime-lock matrix contract coverage for packaged provider metadata.",
      exception: "",
    },
    {
      id: "desktop-shell.desktop-launch-mode-contracts",
      title: "Desktop launch mode contracts",
      family: "desktop-shell",
      entrypointType: "core-package-script",
      entrypoint: "bazel:desktop:launch-mode:contracts",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "desktop",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/desktop_mode_contract.test.cjs",
        "core/scripts/desktop_prepare.test.cjs",
        "core/scripts/desktop_tauri_entry.test.cjs",
      ],
      dependencyCrates: [],
      notes: "Desktop launch mode, prepare, and Tauri entry contracts that gate parity-safe startup behavior.",
      exception: "",
    },
    {
      id: "distribution-install.desktop-bundle-contracts",
      title: "Desktop bundle contracts",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "bazel:desktop:bundle:contracts",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "distribution",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/desktop_import_bundles.test.cjs",
        "core/scripts/desktop_normalize_bundle_permissions.test.cjs",
        "core/scripts/desktop_icon_reps.test.cjs",
      ],
      dependencyCrates: [],
      notes: "Bundle import, permissions, and icon contracts for packaged desktop artifacts.",
      exception: "",
    },
    {
      id: "distribution-install.bundled-harness-dependency-contracts",
      title: "Bundled harness dependency contracts",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "bazel:bundled-harness:dependency:contracts",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "distribution",
      sourceGlobs: [
        "core/package.json",
        "scripts/tests/providers_e2e_darwin_codex_fallback_guard.sh",
        "scripts/tests/ensure_bundled_harnesses_droid_dependencies.sh",
        "scripts/providers_e2e.sh",
        "scripts/ensure_bundled_harnesses.sh",
      ],
      dependencyCrates: [],
      notes: "Contracts for bundled harness dependency layout and codex fallback-arch guards.",
      exception: "",
    },
    {
      id: "provider-auth.provider-auth-validate",
      title: "Provider auth matrix validation",
      family: "provider-auth",
      entrypointType: "core-package-script",
      entrypoint: "bazel:provider-auth:validate",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "provider-auth",
      sourceGlobs: PROVIDER_AUTH_VALIDATE_GLOBS,
      dependencyCrates: [],
      notes: "Provider auth matrix manifest and secret-contract validation used in ctx-main.",
      exception: "",
    },
    {
      id: "provider-auth.desktop-e2e-preflight-contracts",
      title: "Desktop e2e preflight contracts",
      family: "provider-auth",
      entrypointType: "core-package-script",
      entrypoint: "bazel:desktop:e2e:preflight:contracts",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "provider-auth",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/desktop_e2e_preflight.test.cjs",
        "core/apps/desktop/automation/**",
        "core/apps/desktop/scripts/automation_runtime_contract.test.cjs",
      ],
      dependencyCrates: [],
      notes: "Desktop E2E preflight contract coverage layered on top of provider auth validation.",
      exception: "",
    },
    {
      id: "distribution-install.desktop-version-check",
      title: "Desktop version check",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "bazel:desktop:check:versions",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "distribution",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/desktop_check_versions.cjs",
        ...RELEASE_CONTRACT_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Version alignment gate for release-facing desktop artifacts.",
      exception: "",
    },
    {
      id: "distribution-install.desktop-runtime-lock-matrix",
      title: "Desktop runtime lock matrix check",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "bazel:desktop:runtime:lock:check-matrix",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "distribution",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/runtime_lock_matrix_consistency.cjs",
        ...RELEASE_CONTRACT_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Matrix consistency gate for desktop runtime lock metadata.",
      exception: "",
    },
    {
      id: "distribution-install.desktop-runtime-lock-validate",
      title: "Desktop runtime lock validate",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "bazel:desktop:runtime:lock:validate",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "distribution",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/runtime_lock_validate.cjs",
        ...RELEASE_CONTRACT_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Final runtime lock validation gate for release preflight.",
      exception: "",
    },
    {
      id: "sandbox-runtime.desktop-sync-resources-contracts",
      title: "Desktop sync resources contracts",
      family: "sandbox-runtime",
      entrypointType: "core-package-script",
      entrypoint: "bazel:desktop:sync-resources:contracts",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "sandbox",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/desktop_sync_resources_remote_daemon_policy.test.cjs",
        "core/scripts/desktop_sync_resources_avf_guest_runtime.test.cjs",
        "core/scripts/desktop_daemon_sidecar_name.test.cjs",
        "core/apps/desktop/automation/wdio.container-assets.test.cjs",
      ],
      dependencyCrates: [],
      notes: "Contracts for desktop sync-resource policy, AVF runtime staging, sidecar naming, and container asset wiring.",
      exception: "",
    },
    {
      id: "provider-runtime.providers-e2e-bundle-contracts",
      title: "Providers e2e bundle contracts",
      family: "provider-runtime",
      entrypointType: "core-package-script",
      entrypoint: "bazel:providers:e2e:bundle:contracts",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "provider-runtime",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/providers_e2e_bundle_isolation.test.cjs",
      ],
      dependencyCrates: [],
      notes: "Provider bundle isolation contracts for packaged E2E flows.",
      exception: "",
    },
    {
      id: "provider-runtime.linux-arm-provider-contracts",
      title: "Linux arm provider contracts",
      family: "provider-runtime",
      entrypointType: "core-package-script",
      entrypoint: "bazel:providers:linux-arm:contracts",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "provider-runtime",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/linux_arm_provider_reliability_matrix.test.cjs",
        "core/scripts/linux_arm_provider_preflight.test.cjs",
        "core/scripts/linux_arm_provider_report_summary.test.cjs",
        "core/scripts/linux_arm_provider_release_gate.test.cjs",
      ],
      dependencyCrates: [],
      notes: "Linux ARM provider preflight, matrix, summary, and release-gate contracts.",
      exception: "",
    },
    {
      id: "toolchain-bootstrap.tauri-tools-lock-contracts",
      title: "Tauri tools lock contracts",
      family: "toolchain-bootstrap",
      entrypointType: "core-package-script",
      entrypoint: "bazel:tauri:tools:lock:contracts",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "toolchain",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/tauri_tools_lock_contract.test.cjs",
      ],
      dependencyCrates: [],
      notes: "Tauri tools lockfile contract coverage for parity-safe desktop packaging inputs.",
      exception: "",
    },
    {
      id: "toolchain-bootstrap.install-desktop-deps-contracts",
      title: "Install desktop deps contracts",
      family: "toolchain-bootstrap",
      entrypointType: "core-package-script",
      entrypoint: "bazel:desktop:deps:contracts",
      surface: "contract",
      oracle: "static-contract",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "toolchain",
      sourceGlobs: [
        "core/package.json",
        "scripts/install_desktop_deps_linux_ubuntu.sh",
        "scripts/tests/install_desktop_deps_linux_ubuntu_contract.sh",
      ],
      dependencyCrates: [],
      notes: "Linux desktop dependency installation contract coverage for parity and release hosts.",
      exception: "",
    },
    {
      id: "web-workbench.web-typecheck",
      title: "Web TypeScript typecheck",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:typecheck",
      surface: "compile",
      oracle: "compiler",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: [
        "core/apps/web/BUILD.bazel",
        "core/apps/web/package.json",
        "core/apps/web/src/**",
        "core/packages/session-supervisor-core/**",
        "core/packages/session-thread-layout/**",
      ],
      dependencyCrates: [],
      notes: "Bazel-backed TypeScript compile truth for the web application and extracted web packages.",
      exception: "",
    },
    {
      id: "web-workbench.session-thread-layout-unit-tests",
      title: "Session thread layout unit tests",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:unit:thread-layout",
      surface: "unit",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: [
        "core/packages/session-thread-layout/**",
      ],
      dependencyCrates: [],
      notes: "Direct hermetic unit coverage for the extracted session thread layout package.",
      exception: "",
      alwaysOnProfiles: ["checkin"],
    },
    {
      id: "web-workbench.pretext-measurement-unit-tests",
      title: "Pretext measurement unit tests",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:pretext:measurement",
      surface: "unit",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: PRETEXT_MEASUREMENT_SOURCE_GLOBS,
      affectedGlobs: [
        "core/packages/session-thread-layout/**",
      ],
      dependencyCrates: [],
      notes: "Focused deterministic transcript measurement, markdown wrapping, pretext virtualizer unit coverage, and the app seam that consumes the extracted session thread layout package.",
      exception: "",
      alwaysOnProfiles: ["checkin"],
    },
    {
      id: "web-workbench.session-supervisor-core-unit-tests",
      title: "Session supervisor core unit tests",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:unit:supervisor-core",
      surface: "unit",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "tiny",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: [
        "core/packages/session-supervisor-core/**",
      ],
      dependencyCrates: [],
      notes: "Direct hermetic unit coverage for the extracted session supervisor core package.",
      exception: "",
      alwaysOnProfiles: ["checkin"],
    },
    {
      id: "web-workbench.web-unit-foundation-shared",
      title: "Web foundation shared unit tests",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:unit:non-pretext:foundation:shared",
      surface: "unit",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: [
        "core/apps/web/src/api/**",
        "core/apps/web/src/assets/**",
        "core/apps/web/src/config/**",
        "core/apps/web/src/eslint/**",
        "core/apps/web/src/generated/**",
        "core/apps/web/src/lib/**",
        "core/apps/web/src/styles/**",
        "core/apps/web/src/testUtils/**",
        "core/apps/web/src/testing/**",
        "core/apps/web/src/utils/**",
        "core/apps/web/src/workbench/**",
        "core/apps/web/src/workers/**",
      ],
      excludeGlobs: PRETEXT_MEASUREMENT_CODE_GLOBS,
      dependencyCrates: [],
      notes: "Hermetic app/web unit coverage for shared foundation, config, utilities, and store-adjacent helpers outside the dedicated state slice.",
      exception: "",
      alwaysOnProfiles: ["checkin"],
    },
    {
      id: "web-workbench.web-unit-foundation-state",
      title: "Web foundation state unit tests",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:unit:non-pretext:foundation:state",
      surface: "unit",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: [
        "core/apps/web/src/state/**",
        "core/apps/web/src/testdata/**",
      ],
      excludeGlobs: PRETEXT_MEASUREMENT_CODE_GLOBS,
      dependencyCrates: [],
      notes: "Hermetic app/web unit coverage for state stores, coordinators, and state-owned fixtures.",
      exception: "",
      alwaysOnProfiles: ["checkin"],
    },
    {
      id: "web-workbench.web-unit-settings-setup",
      title: "Web settings and setup unit tests",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:unit:non-pretext:settings-setup",
      surface: "unit",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: [
        "core/apps/web/src/pages/settings/**",
        "core/apps/web/src/pages/workspaceSetup/**",
        "core/apps/web/src/pages/diagnostics/**",
        "core/apps/web/src/pages/launcher/**",
        "core/apps/web/src/pages/workspaceBootstrapGate*",
        "core/apps/web/src/pages/WorkspaceSetupPage*",
      ],
      excludeGlobs: PRETEXT_MEASUREMENT_CODE_GLOBS,
      dependencyCrates: [],
      notes: "Hermetic app/web unit coverage for settings, launcher, diagnostics, and workspace setup flows.",
      exception: "",
      alwaysOnProfiles: ["checkin"],
    },
    {
      id: "web-workbench.web-unit-workbench-surface-app",
      title: "Web workbench surface app unit tests",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:unit:non-pretext:workbench:surface:app",
      surface: "unit",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: [
        "core/apps/web/playwright.shared.ts",
        "core/apps/web/playwright.shared.test.ts",
        "core/apps/web/src/*",
        "core/apps/web/src/App*",
        "core/apps/web/src/components/**",
        "core/apps/web/src/pages/**",
      ],
      excludeGlobs: PRETEXT_MEASUREMENT_CODE_GLOBS.concat([
        "core/apps/web/src/pages/settings/**",
        "core/apps/web/src/pages/workspaceSetup/**",
        "core/apps/web/src/pages/diagnostics/**",
        "core/apps/web/src/pages/launcher/**",
        "core/apps/web/src/pages/SessionPage*",
        "core/apps/web/src/pages/session*",
        "core/apps/web/src/pages/useSession*",
        "core/apps/web/src/pages/sessionView/**",
        "core/apps/web/src/pages/sessionThread/**",
        "core/apps/web/src/pages/workbenchShell/**",
        "core/apps/web/src/pages/workspaceBootstrapGate*",
        "core/apps/web/src/pages/WorkspaceSetupPage*",
      ]),
      dependencyCrates: [],
      notes: "Hermetic app/web unit coverage for root app wiring, workbench chrome, and non-session pages outside the dedicated pretext, settings/setup, and shell/session slices.",
      exception: "",
      alwaysOnProfiles: ["checkin"],
    },
    {
      id: "web-workbench.web-unit-workbench-surface-session",
      title: "Web workbench surface session unit tests",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:unit:non-pretext:workbench:surface:session",
      surface: "unit",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: [
        "core/apps/web/src/pages/SessionPage*",
        "core/apps/web/src/pages/session*",
        "core/apps/web/src/pages/useSession*",
        "core/apps/web/src/pages/sessionView/**",
        "core/apps/web/src/pages/sessionThread/**",
      ],
      excludeGlobs: PRETEXT_MEASUREMENT_CODE_GLOBS,
      dependencyCrates: [],
      notes: "Hermetic app/web unit coverage for the session page, transcript controllers, and session-specific view state outside the dedicated pretext slice.",
      exception: "",
      alwaysOnProfiles: ["checkin"],
    },
    {
      id: "web-workbench.web-unit-workbench-shell",
      title: "Web workbench shell unit tests",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:unit:non-pretext:workbench:shell",
      surface: "unit",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: [
        "core/apps/web/src/pages/workbenchShell/**",
      ],
      excludeGlobs: PRETEXT_MEASUREMENT_CODE_GLOBS,
      dependencyCrates: [],
      notes: "Hermetic app/web unit coverage for the workbench shell chrome, task list, and session slot presentation surface.",
      exception: "",
      alwaysOnProfiles: ["checkin"],
    },
    {
      id: "web-workbench.web-unit-misc",
      title: "Web misc unit tests",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:unit:non-pretext:misc",
      surface: "unit",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: [
        "core/apps/web/scripts/**",
      ],
      dependencyCrates: [],
      notes: "Hermetic app/web unit coverage for remaining non-pretext script-owned tests outside the main src buckets.",
      exception: "",
      alwaysOnProfiles: ["checkin"],
    },
    {
      id: "web-workbench.web-unit-meta",
      title: "Web unit suite meta gate",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:unit:non-pretext",
      surface: "unit",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "fast",
      requirements: ["linux", "buildbuddy-rbe"],
      stability: "stable",
      execution: "bazel-rbe-preferred",
      owner: "web-workbench",
      sourceGlobs: [
        "core/apps/web/BUILD.bazel",
        "core/apps/web/package.json",
      ],
      affectedGlobs: [
        "core/packages/session-supervisor-core/**",
      ],
      dependencyCrates: [],
      notes: "Broad non-pretext suite for meta changes and extracted supervisor-package consumer coverage where shard attribution is not yet explicit.",
      exception: "",
      alwaysOnProfiles: ["checkin"],
    },
    {
      id: "web-workbench.web-premerge-required",
      title: "Web premerge required suite",
      family: "web-workbench",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:e2e:premerge",
      surface: "system",
      oracle: "golden-flow",
      world: "simulated",
      cost: "fast",
      requirements: ["linux", "browser"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "web-workbench",
      sourceGlobs: [
        "core/package.json",
        "core/apps/web/package.json",
        "core/apps/web/BUILD.bazel",
        "core/apps/web/e2e/BUILD.bazel",
        "core/apps/web/e2e/web_e2e_test.bzl",
        "core/apps/web/playwright*.config.ts",
        "core/apps/web/playwright.shared.ts",
        "core/apps/web/src/state/**",
        "core/apps/web/src/api/**",
        "core/apps/web/e2e/fixtures/**",
        "core/apps/web/e2e/utils/**",
        "core/apps/web/e2e/suites/premerge_required.txt",
        "core/apps/web/scripts/start-e2e-server.mjs",
        "core/apps/web/scripts/run-e2e-bazel-runtime.mjs",
        "core/apps/web/scripts/run-e2e-bazel-runtime.sh",
      ],
      dependencyCrates: [],
      notes: "Canonical premerge-required browser suite.",
      exception: "",
    },
    {
      id: "desktop-shell.image-paste",
      title: "Desktop image paste automation",
      family: "desktop-shell",
      entrypointType: "core-package-script",
      entrypoint: "verify:desktop:image-paste",
      surface: "system",
      oracle: "golden-flow",
      world: "simulated",
      cost: "medium",
      requirements: ["mac", "single-mac"],
      stability: "stable",
      execution: "script-local",
      owner: "desktop",
      sourceGlobs: [
        "core/package.json",
        "core/apps/desktop/package.json",
        "core/apps/desktop/automation/specs/workbench-image-paste.spec.cjs",
        "scripts/desktop_smoke_with_infisical.sh",
      ],
      dependencyCrates: [],
      notes: "Desktop image paste automation flow.",
      exception: "Intentional single-Mac desktop automation truth; scarce UI/device coverage is the floor here, not Bazel addressability.",
    },
    {
      id: "desktop-shell.image-drag-drop",
      title: "Desktop image drag/drop automation",
      family: "desktop-shell",
      entrypointType: "core-package-script",
      entrypoint: "verify:desktop:image-drag-drop",
      surface: "system",
      oracle: "golden-flow",
      world: "simulated",
      cost: "medium",
      requirements: ["mac", "single-mac"],
      stability: "stable",
      execution: "script-local",
      owner: "desktop",
      sourceGlobs: [
        "core/package.json",
        "core/apps/desktop/package.json",
        "core/apps/desktop/automation/specs/workbench-image-drag-drop.spec.cjs",
        "scripts/desktop_smoke_with_infisical.sh",
      ],
      dependencyCrates: [],
      notes: "Desktop image drag/drop automation flow.",
      exception: "Intentional single-Mac desktop automation truth; scarce UI/device coverage is the floor here, not Bazel addressability.",
    },
    {
      id: "desktop-shell.notifications-contracts",
      title: "Desktop notification contracts",
      family: "desktop-shell",
      entrypointType: "core-package-script",
      entrypoint: "verify:desktop:notifications-contracts",
      surface: "integration",
      oracle: "direct-assertion",
      world: "hermetic",
      cost: "fast",
      requirements: ["mac"],
      stability: "stable",
      execution: "script-local",
      owner: "desktop",
      sourceGlobs: [
        "core/package.json",
        "core/apps/desktop/package.json",
        "core/apps/desktop/scripts/test_notification_contracts.sh",
        "core/apps/desktop/automation/notification-signed-smoke.contract.test.cjs",
        "core/apps/desktop/src-tauri/src/desktop_attention.rs",
        "core/apps/desktop/src-tauri/src/desktop_notifications.rs",
        "core/apps/desktop/src-tauri/src/desktop_deeplink.rs",
        "core/apps/desktop/src-tauri/src/desktop_windows.rs",
      ],
      dependencyCrates: [],
      notes: "Deterministic Rust contracts for desktop attention aggregation, notification payloads, deep-link parsing, and workspace routing.",
      exception: "ctx-desktop still sits outside the main Cargo workspace and needs a minimal Tauri dist stub for macro expansion; keep this script-local until the desktop crate becomes directly addressable.",
    },
    {
      id: "distribution-install.desktop-smoke-local",
      title: "Desktop smoke local install",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "verify:desktop:smoke:local",
      surface: "system",
      oracle: "golden-flow",
      world: "local-packaged-artifact",
      cost: "medium",
      requirements: ["mac", "network", "single-mac"],
      stability: "stable",
      execution: "script-local",
      owner: "desktop",
      sourceGlobs: [
        "core/package.json",
        "scripts/desktop_smoke_with_infisical.sh",
      ],
      dependencyCrates: [],
      notes: "Desktop/local install smoke path.",
      exception: "Intentional local-packaged-artifact install truth on the shared Mac; keep script-local unless local smoke becomes a measured bottleneck.",
    },
    {
      id: "distribution-install.desktop-remote-contracts",
      title: "Desktop remote docker contracts",
      family: "distribution-install",
      entrypointType: "core-package-script",
      entrypoint: "verify:desktop:remote-contracts",
      surface: "system",
      oracle: "golden-flow",
      world: "local-packaged-artifact",
      cost: "medium",
      requirements: ["mac", "docker", "network", "single-mac"],
      stability: "stable",
      execution: "script-local",
      owner: "desktop",
      sourceGlobs: [
        "core/package.json",
        "core/apps/desktop/package.json",
        "core/apps/desktop/scripts/test_remote_docker_contracts.sh",
      ],
      dependencyCrates: [],
      notes: "Desktop remote-contract Docker validation paired with local smoke.",
      exception: "Intentional local-packaged-artifact and Docker truth on the shared Mac; keep script-local unless this lane becomes a measured bottleneck.",
    },
    {
      id: "updates-release.updater-native-smoke",
      title: "Updater native smoke",
      family: "updates-release",
      entrypointType: "core-package-script",
      entrypoint: "verify:e2e:updater:smoke:native",
      surface: "artifact",
      oracle: "artifact-integrity",
      world: "local-packaged-artifact",
      cost: "medium",
      requirements: ["linux", "network"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "updates-release",
      sourceGlobs: [
        "core/package.json",
        "scripts/tests/release_manifest_concurrency_smoke.sh",
        "scripts/tests/release_promote_supabase_latest_smoke.sh",
        "scripts/tests/updater_contract_validate_smoke.sh",
        "scripts/tests/release_verify_supabase_updater_smoke.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Release/updater native smoke and manifest integrity checks.",
      exception: "Intentional artifact-tail boundary for updater-manifest and local packaged-artifact truth; keep outside Bazel because it validates staged release state and publish-path side effects.",
    },
    {
      id: "updates-release.updater-linux-proof",
      title: "Updater Linux proof",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/tests/updater_linux_release_truth.sh",
      surface: "promotion",
      oracle: "golden-flow",
      world: "external-service",
      cost: "slow",
      requirements: ["linux", "network"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "updates-release",
      sourceGlobs: [
        "core/apps/desktop/package.json",
        "core/apps/desktop/automation/specs/updater-native-smoke.spec.cjs",
        "core/apps/desktop/automation/specs/helpers/updater_native_proof.cjs",
        "scripts/release_runtime_install_smoke.sh",
        "scripts/tests/updater_linux_release_truth.sh",
        "scripts/tests/linux_local_install_sandbox_release_truth.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Real Linux install->update->provider/runtime->workspace proof against published release artifacts.",
      exception: "Intentional artifact-tail proof on a real Linux host; keep outside Bazel because it consumes published artifacts, real provider credentials, and installed AppImage side effects.",
    },
    {
      id: "updates-release.updater-remote-daemon-proof",
      title: "Updater remote daemon proof",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/tests/updater_remote_daemon_e2e.sh",
      surface: "promotion",
      oracle: "golden-flow",
      world: "external-service",
      cost: "slow",
      requirements: ["linux", "network"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "updates-release",
      sourceGlobs: [
        "core/apps/desktop/package.json",
        "core/apps/desktop/automation/specs/updater-remote-daemon-e2e.spec.cjs",
        "core/apps/desktop/automation/specs/helpers/remote_updater_proof.cjs",
        "core/apps/desktop/automation/helpers/remote_fixture_contract.cjs",
        "scripts/lib/updater_e2e_drill_full_paths.sh",
        "scripts/tests/updater_remote_daemon_e2e.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Real remote daemon updater proof for idle connect, immediate incompatible reconnect, daemon-owned no-client update, and explicitly-configured compatible busy branches.",
      exception: "Intentional artifact-tail proof that consumes published artifacts plus real SSH-host side effects; keep explicit and script-local instead of hiding fleet orchestration inside Bazel.",
    },
    {
      id: "updates-release.updater-web-e2e-suite",
      title: "Release updater web e2e suite",
      family: "updates-release",
      entrypointType: "core-package-script",
      entrypoint: "bazel:web:e2e:release:retry",
      surface: "system",
      oracle: "golden-flow",
      world: "local-packaged-artifact",
      cost: "medium",
      requirements: ["linux", "browser"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "updates-release",
      sourceGlobs: [
        "core/package.json",
        "scripts/ci_retry.sh",
        "core/apps/web/e2e/**",
        "core/apps/web/e2e/suites/release_required.txt",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Retry-wrapped release-required browser suite once Linux webkit prerequisites are present.",
      exception: "",
    },
    {
      id: "artifacts-provenance.codex-archive-artifacts",
      title: "Codex archive artifact gate",
      family: "artifacts-provenance",
      entrypointType: "core-package-script",
      entrypoint: "bazel:bundles:codex-archive-artifacts",
      surface: "artifact",
      oracle: "artifact-integrity",
      world: "local-packaged-artifact",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "ci-release",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/provider_matrix_archive_artifact_gate.cjs",
        "tools/bazel/codex_archive_artifact_gate.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Archive artifact presence and merge integrity gate.",
      exception: "",
    },
    {
      id: "artifacts-provenance.codex-provenance",
      title: "Codex provenance gate",
      family: "artifacts-provenance",
      entrypointType: "core-package-script",
      entrypoint: "bazel:bundles:codex-provenance",
      surface: "artifact",
      oracle: "artifact-integrity",
      world: "local-packaged-artifact",
      cost: "fast",
      requirements: ["linux"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "ci-release",
      sourceGlobs: [
        "core/package.json",
        "scripts/tests/codex_release_provenance_policy.sh",
        "tools/bazel/codex_provenance_policy.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Provenance policy enforcement for bundled artifacts.",
      exception: "",
    },
    {
      id: "updates-release.release-stage-linux-x64",
      title: "Release stage linux x64",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_release_stage_linux_x64.sh",
      surface: "artifact",
      oracle: "artifact-integrity",
      world: "local-packaged-artifact",
      cost: "slow",
      requirements: ["linux"],
      stability: "stable",
      execution: "script-local",
      owner: "ci-release",
      sourceGlobs: [
        "scripts/buildkite/release_pipeline_lib.sh",
        "scripts/buildkite/run_release_stage_linux_x64.sh",
        "scripts/buildbuddy/run_release.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Buildkite-owned Linux x64 release stage and stage-archive upload boundary.",
      exception: "Intentional script-local Linux packaging stage; it assembles staged release artifacts, touches host packaging toolchains, and should stay explicit instead of hiding mutable packaging state behind a coarse Bazel shell.",
    },
    {
      id: "updates-release.release-stage-linux-arm64",
      title: "Release stage linux arm64",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_release_stage_linux_arm64.sh",
      surface: "artifact",
      oracle: "artifact-integrity",
      world: "local-packaged-artifact",
      cost: "slow",
      requirements: ["linux-arm64"],
      stability: "stable",
      execution: "script-local",
      owner: "ci-release",
      sourceGlobs: [
        "scripts/buildkite/release_pipeline_lib.sh",
        "scripts/buildkite/run_release_stage_linux_arm64.sh",
        "scripts/buildbuddy/run_release.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Buildkite-owned Linux arm64 release stage and stage-archive upload boundary.",
      exception: "Intentional script-local Linux packaging stage for arm64 artifact truth; keep explicit because the remaining cost is packaging and archive assembly on the real release host, not hermetic compile work.",
    },
    {
      id: "updates-release.mac-preview-macos-arm64",
      title: "Mac preview macos arm64",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_mac_preview_build.sh",
      surface: "artifact",
      oracle: "artifact-integrity",
      world: "local-packaged-artifact",
      cost: "medium",
      requirements: ["mac", "single-mac"],
      stability: "stable",
      execution: "script-local",
      owner: "ci-release",
      sourceGlobs: [
        ".buildkite/pipelines/mac-preview.yml",
        "scripts/buildkite/run_mac_preview_build.sh",
        "scripts/buildbuddy/check_macos_publish_prereqs.sh",
        "scripts/buildbuddy/run_release_macos.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Fast Apple Silicon preview app boundary for promoted main desktop feedback, plus the preview macos-arm64 updater manifest entry required by remote bootstrap freshness.",
      exception: "Intentional script-local shared-Mac preview boundary; it reuses the release-stage signing path and publishes only lightweight preview updater metadata so preview feedback stays much faster than full canary.",
    },
    {
      id: "updates-release.release-stage-macos",
      title: "Release stage macos",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_release_stage_macos.sh",
      surface: "artifact",
      oracle: "artifact-integrity",
      world: "local-packaged-artifact",
      cost: "slow",
      requirements: ["mac", "single-mac", "network"],
      stability: "stable",
      execution: "script-local",
      owner: "ci-release",
      sourceGlobs: [
        "scripts/buildkite/release_pipeline_lib.sh",
        "scripts/buildkite/run_release_stage_macos.sh",
        "scripts/buildbuddy/run_release_macos.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Buildkite-owned combined macOS stage boundary for the shared Mac queue.",
      exception: "Intentional script-local shared-Mac stage; this lane owns scarce Mac packaging, signing prerequisites, and real host cleanup, so it should remain an explicit single-Mac boundary rather than a hidden Bazel wrapper.",
    },
    {
      id: "updates-release.release-finalize-macos",
      title: "Release finalize macos",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_release_finalize_macos.sh",
      surface: "artifact",
      oracle: "artifact-integrity",
      world: "local-packaged-artifact",
      cost: "slow",
      requirements: ["mac", "single-mac", "network"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "ci-release",
      sourceGlobs: [
        "scripts/buildkite/download_artifacts_with_retry.sh",
        "scripts/buildkite/release_pipeline_lib.sh",
        "scripts/buildkite/run_release_finalize_macos.sh",
        "scripts/buildbuddy/run_release_macos_finalize.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Buildkite-owned macOS finalize/notary boundary that consumes staged mac artifacts.",
      exception: "Intentional artifact-tail boundary for notarization and stapling on the shared Mac; Apple service calls and retryable signed-artifact handling are the real work here, not hermetic build graph execution.",
    },
    {
      id: "updates-release.release-finalize",
      title: "Release finalize",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_release_finalize.sh",
      surface: "promotion",
      oracle: "live-publish",
      world: "external-service",
      cost: "medium",
      requirements: ["linux", "network"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "ci-release",
      sourceGlobs: [
        "scripts/buildkite/download_artifacts_with_retry.sh",
        "scripts/buildkite/release_pipeline_lib.sh",
        "scripts/buildkite/run_release_finalize.sh",
        "scripts/buildbuddy/run_release_finalize.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Buildkite-owned release finalize boundary that consumes staged platform archives, publishes versioned release state, verifies it, promotes latest, and emits release evidence.",
      exception: "Intentional artifact-tail publish boundary; it must consume already-staged artifacts and talk to external release services without rebuilding from source.",
    },
    {
      id: "updates-release.release-proof-linux-updater-smoke",
      title: "Release proof linux updater smoke",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_release_proof_linux_updater_smoke.sh",
      surface: "promotion",
      oracle: "golden-flow",
      world: "external-service",
      cost: "slow",
      requirements: ["linux", "network"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "ci-release",
      sourceGlobs: [
        "scripts/buildkite/run_release_proof_linux_updater_smoke.sh",
        "scripts/tests/updater_linux_release_truth.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Buildkite-owned post-publish Linux updater smoke proof against the canary/e2e channel.",
      exception: "Intentional artifact-tail proof on a real Linux host; this lane proves published updater behavior and must report separately from provider/runtime and workspace proof.",
    },
    {
      id: "updates-release.release-proof-linux-provider-matrix",
      title: "Release proof linux provider matrix",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_release_proof_linux_provider_matrix.sh",
      surface: "promotion",
      oracle: "golden-flow",
      world: "external-service",
      cost: "slow",
      requirements: ["linux", "network"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "ci-release",
      sourceGlobs: [
        "core/apps/desktop/scripts/run_harness_install_matrix.sh",
        "scripts/buildkite/run_release_proof_linux_provider_matrix.sh",
        "scripts/tests/updater_linux_release_truth.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Buildkite-owned pre-publish Linux host/sandbox harness-install matrix against the staged AppImage bundle.",
      exception: "Intentional staged-artifact proof on a real Linux host; provider/runtime installability is release evidence and must block publish independently from updater and workspace proof.",
    },
    {
      id: "updates-release.release-proof-linux-clean-workspace",
      title: "Release proof linux clean workspace",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_release_proof_linux_clean_workspace.sh",
      surface: "promotion",
      oracle: "golden-flow",
      world: "external-service",
      cost: "slow",
      requirements: ["linux", "network"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "ci-release",
      sourceGlobs: [
        "core/apps/desktop/automation/specs/workspace-wizard.spec.cjs",
        "scripts/buildkite/run_release_proof_linux_clean_workspace.sh",
        "scripts/tests/updater_linux_release_truth.sh",
        "scripts/desktop_smoke_with_infisical.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Buildkite-owned pre-publish clean Linux workspace proof against the staged AppImage bundle.",
      exception: "Intentional staged-artifact proof on a real Linux host; workspace launch truth depends on shipped app, local daemon state, and real provider credentials.",
    },
    {
      id: "updates-release.release-proof-remote-updater",
      title: "Release proof remote updater",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_release_proof_remote_updater.sh",
      surface: "promotion",
      oracle: "golden-flow",
      world: "external-service",
      cost: "slow",
      requirements: ["linux", "network"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "ci-release",
      sourceGlobs: [
        "core/apps/desktop/automation/specs/updater-remote-daemon-e2e.spec.cjs",
        "core/apps/desktop/automation/specs/helpers/remote_updater_proof.cjs",
        "scripts/buildkite/run_release_proof_remote_updater.sh",
        "scripts/tests/updater_remote_daemon_e2e.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Buildkite-owned post-publish remote daemon updater proof against strict published artifacts.",
      exception: "Intentional artifact-tail proof that consumes published artifacts plus real SSH-host side effects; it must report separately from local Linux proof lanes.",
    },
    {
      id: "updates-release.stable-promotion",
      title: "Stable artifact promotion",
      family: "updates-release",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_release_stable_promote.sh",
      surface: "promotion",
      oracle: "live-publish",
      world: "external-service",
      cost: "medium",
      requirements: ["linux", "network"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "ci-release",
      sourceGlobs: [
        "scripts/buildkite/release_pipeline_lib.sh",
        "scripts/buildkite/run_release_stable_promote.sh",
        "core/scripts/release_promote_canary_to_stable.cjs",
        "scripts/release_verify_supabase.sh",
        "scripts/release_promote_supabase_latest.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Buildkite-owned stable promotion boundary that verifies canary artifacts for the same SHA, copies exact artifact objects into stable storage, rewrites stable manifests, and promotes latest without rebuilding.",
      exception: "Intentional artifact-tail stable publish boundary; it must consume canary-proven published artifacts and must not rebuild or recompute provider state.",
    },
    {
      id: "updates-release.release-e2e-publish",
      title: "Release E2E publish",
      family: "updates-release",
      entrypointType: "core-package-script",
      entrypoint: "release:e2e:publish",
      surface: "promotion",
      oracle: "live-publish",
      world: "published-artifact",
      cost: "slow",
      requirements: ["network", "single-mac"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "updates-release",
      sourceGlobs: [
        "core/package.json",
        "scripts/release_e2e_with_infisical.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Live publish path for release E2E.",
      exception: "Intentional published-artifact tail that exercises live release publication and install/update truth; keep explicit and out of Bazel because the value is external-service verification, not compile reuse.",
    },
    {
      id: "updates-release.release-e2e-verify",
      title: "Release E2E verify",
      family: "updates-release",
      entrypointType: "core-package-script",
      entrypoint: "release:e2e:verify",
      surface: "promotion",
      oracle: "live-publish",
      world: "published-artifact",
      cost: "medium",
      requirements: ["network"],
      stability: "stable",
      execution: "artifact-tail",
      owner: "updates-release",
      sourceGlobs: [
        "core/package.json",
        "scripts/release_e2e_with_infisical.sh",
        ...RELEASE_RELEVANT_GLOBS,
      ],
      dependencyCrates: [],
      notes: "Published artifact verification path.",
      exception: "Intentional published-artifact verification tail for already-published release state; it should stay explicit because it validates real remote artifacts and updater behavior.",
    },
    {
      id: "resilience-performance.agent-loop-main-band-benchmark",
      title: "Agent loop main-band benchmark evidence",
      family: "resilience-performance",
      entrypointType: "repo-shell-script",
      entrypoint: "scripts/buildkite/run_nightly_benchmark_evidence.sh",
      surface: "performance",
      oracle: "budget",
      world: "hermetic",
      cost: "medium",
      requirements: ["linux"],
      stability: "stable",
      execution: "script-local",
      owner: "ci-release",
      sourceGlobs: [
        "scripts/buildkite/run_nightly_benchmark_evidence.sh",
        "scripts/buildkite/taxonomy_pipeline_lib.sh",
        "core/package.json",
        "core/scripts/sdlc_agent_loop_benchmark.cjs",
        "core/scripts/sdlc_host_budget_benchmark.cjs",
      ],
      dependencyCrates: [],
      notes: "Advisory nightly benchmark evidence for host-budget drift on the checked-in main-band preset.",
      exception: "Intentional script-local nightly operator benchmark; it measures host-budget drift and emits evidence, not product behavior inside the Bazel graph.",
    },
    {
      id: "resilience-performance.anomaly.ctx-http-fault-matrix",
      title: "Anomaly ctx-http fault matrix",
      family: "resilience-performance",
      entrypointType: "core-package-script",
      entrypoint: "bazel:anomaly:ctx-http:fault-matrix",
      surface: "resilience",
      oracle: "fault-injection",
      world: "simulated",
      cost: "slow",
      requirements: ["linux", "long-running"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "reliability",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/run-anomaly-suite.sh",
        "core/crates/ctx-http/tests/fault_matrix.rs",
      ],
      dependencyCrates: ["ctx-http"],
      notes: "Fault-injection replay and stream anomaly coverage for ctx-http.",
      exception: "",
    },
    {
      id: "resilience-performance.anomaly.ctx-http-hot-endpoints-no-db",
      title: "Anomaly ctx-http hot endpoints no db",
      family: "resilience-performance",
      entrypointType: "core-package-script",
      entrypoint: "bazel:anomaly:ctx-http:hot-endpoints-no-db",
      surface: "resilience",
      oracle: "fault-injection",
      world: "simulated",
      cost: "slow",
      requirements: ["linux", "long-running"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "reliability",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/run-anomaly-suite.sh",
        "core/crates/ctx-http/tests/hot_endpoints_no_db.rs",
      ],
      dependencyCrates: ["ctx-http"],
      notes: "Hot endpoint anomaly coverage without a backing database.",
      exception: "",
    },
    {
      id: "resilience-performance.anomaly.ctx-store-fault-injection",
      title: "Anomaly ctx-store fault injection",
      family: "resilience-performance",
      entrypointType: "core-package-script",
      entrypoint: "bazel:anomaly:ctx-store:fault-injection",
      surface: "resilience",
      oracle: "fault-injection",
      world: "simulated",
      cost: "slow",
      requirements: ["linux", "long-running"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "reliability",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/run-anomaly-suite.sh",
        "core/crates/ctx-store/**",
      ],
      dependencyCrates: ["ctx-store"],
      notes: "Fault-injection coverage for ctx-store.",
      exception: "",
    },
    {
      id: "resilience-performance.fuzz.providers",
      title: "Fuzz regression providers",
      family: "resilience-performance",
      entrypointType: "core-package-script",
      entrypoint: "bazel:fuzz:providers",
      surface: "adversarial",
      oracle: "fault-injection",
      world: "hermetic",
      cost: "slow",
      requirements: ["linux", "long-running"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "reliability",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/run-fuzz-regression.sh",
        "core/crates/ctx-providers/**",
      ],
      dependencyCrates: ["ctx-providers"],
      notes: "Fuzz regression corpus coverage for provider normalization and ACP payloads.",
      exception: "",
    },
    {
      id: "resilience-performance.fuzz.mcp",
      title: "Fuzz regression mcp",
      family: "resilience-performance",
      entrypointType: "core-package-script",
      entrypoint: "bazel:fuzz:mcp",
      surface: "adversarial",
      oracle: "fault-injection",
      world: "hermetic",
      cost: "slow",
      requirements: ["linux", "long-running"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "reliability",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/run-fuzz-regression.sh",
        "core/crates/ctx-mcp/**",
      ],
      dependencyCrates: ["ctx-mcp"],
      notes: "Fuzz regression coverage for MCP tool payload corpora.",
      exception: "",
    },
    {
      id: "resilience-performance.fuzz.workspace-payloads",
      title: "Fuzz regression workspace payloads",
      family: "resilience-performance",
      entrypointType: "core-package-script",
      entrypoint: "bazel:fuzz:workspace-payloads",
      surface: "adversarial",
      oracle: "fault-injection",
      world: "hermetic",
      cost: "slow",
      requirements: ["linux", "long-running"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "reliability",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/run-fuzz-regression.sh",
        "core/crates/ctx-core/tests/workspace_payload_corpus.rs",
        "core/crates/ctx-core/tests/corpus/workspace_payloads/**",
      ],
      dependencyCrates: ["ctx-core"],
      notes: "Corpus regression coverage for workspace payload handling.",
      exception: "",
    },
    {
      id: "resilience-performance.fuzz.release-manifests",
      title: "Fuzz regression release manifests",
      family: "resilience-performance",
      entrypointType: "core-package-script",
      entrypoint: "bazel:fuzz:release-manifests",
      surface: "adversarial",
      oracle: "fault-injection",
      world: "hermetic",
      cost: "slow",
      requirements: ["linux", "long-running"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "reliability",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/run-fuzz-regression.sh",
        "core/crates/ctx-http/tests/release_manifest_corpus.rs",
        "core/crates/ctx-http/tests/corpus/release_manifests/**",
      ],
      dependencyCrates: ["ctx-http"],
      notes: "Corpus regression coverage for updater and release manifest parsing.",
      exception: "",
    },
    {
      id: "resilience-performance.fuzz.desktop-ipc",
      title: "Fuzz regression desktop ipc",
      family: "resilience-performance",
      entrypointType: "core-package-script",
      entrypoint: "bazel:fuzz:desktop-ipc",
      surface: "adversarial",
      oracle: "fault-injection",
      world: "hermetic",
      cost: "slow",
      requirements: ["linux", "long-running"],
      stability: "stable",
      execution: "bazel-addressable",
      owner: "reliability",
      sourceGlobs: [
        "core/package.json",
        "core/scripts/run-fuzz-regression.sh",
        "core/apps/web/src/utils/desktop.corpus.test.ts",
        "core/apps/web/src/utils/testdata/desktop-ipc/**",
      ],
      dependencyCrates: [],
      notes: "Corpus regression coverage for desktop IPC payload normalization on the web side.",
      exception: "",
    },
  ];
}

function getCorePackageScripts() {
  return new Set(Object.keys(packageJson.scripts || {}));
}

function validateEntrypoint(entry) {
  switch (entry.entrypointType) {
    case "file": {
      const abs = path.join(repoRoot, entry.entrypoint);
      if (!fs.existsSync(abs)) {
        throw new Error(`missing file entrypoint for ${entry.id}: ${entry.entrypoint}`);
      }
      return;
    }
    case "core-package-script": {
      if (!getCorePackageScripts().has(entry.entrypoint)) {
        throw new Error(`missing core package script for ${entry.id}: ${entry.entrypoint}`);
      }
      return;
    }
    case "repo-shell-script": {
      const abs = path.join(repoRoot, entry.entrypoint);
      if (!fs.existsSync(abs)) {
        throw new Error(`missing repo shell script entrypoint for ${entry.id}: ${entry.entrypoint}`);
      }
      return;
    }
    case "ctx-http-suite": {
      if (!CTX_HTTP_SUITES.some((suite) => suite.name === entry.entrypoint)) {
        throw new Error(`missing ctx-http suite for ${entry.id}: ${entry.entrypoint}`);
      }
      return;
    }
    case "rust-crate-gate": {
      if (entry.entrypoint === "ctx-http") {
        throw new Error(`ctx-http must stay taxonomy-addressed via suite entries, not rust-crate-gate: ${entry.id}`);
      }
      if (!rustWorkspaceGraph.cratesByName.has(entry.entrypoint)) {
        throw new Error(`missing Rust crate gate for ${entry.id}: ${entry.entrypoint}`);
      }
      return;
    }
    case "provider-matrix-lane": {
      const [, lane] = entry.entrypoint.split("#");
      if (!lane || !providerMatrix.cells.some((cell) => cell.lane === lane)) {
        throw new Error(`missing provider matrix lane for ${entry.id}: ${entry.entrypoint}`);
      }
      return;
    }
    case "web-e2e-spec": {
      const abs = path.join(repoRoot, entry.entrypoint);
      if (!fs.existsSync(abs)) {
        throw new Error(`missing web e2e spec for ${entry.id}: ${entry.entrypoint}`);
      }
      return;
    }
    default:
      throw new Error(`unknown entrypoint type for ${entry.id}: ${entry.entrypointType}`);
  }
}

function buildTaxonomyRegistry() {
  const familiesById = getFamiliesById();
  const entries = sortEntries([
    ...buildStaticEntries(),
    ...buildCtxHttpEntries(),
    ...buildRustEntries(),
    ...buildProviderMatrixEntries(),
    ...buildHarnessInstallMatrixEntries(),
    ...buildWebE2EEntries(),
  ].map((entry) => validateEntry(entry, familiesById)));

  const ids = new Set();
  for (const entry of entries) {
    if (ids.has(entry.id)) {
      throw new Error(`duplicate taxonomy entry id: ${entry.id}`);
    }
    ids.add(entry.id);
  }
  return entries;
}

function validateTaxonomyRegistry(entries = buildTaxonomyRegistry()) {
  for (const entry of entries) {
    validateEntrypoint(entry);
  }

  const ctxHttpValidation = validateCtxHttpSuites(coreRoot);
  if (ctxHttpValidation.duplicates.length > 0 || ctxHttpValidation.missing.length > 0 || ctxHttpValidation.unknown.length > 0) {
    throw new Error(`ctx-http suite inventory invalid: ${JSON.stringify(ctxHttpValidation)}`);
  }

  const suiteMap = readWebSuiteMap();
  const allAssignedSpecs = new Set();
  for (const specs of suiteMap.values()) {
    for (const spec of specs) {
      allAssignedSpecs.add(spec);
    }
  }
  const actualSpecs = fs
    .readdirSync(webE2ERoot)
    .filter((entry) => entry.endsWith(".spec.ts"))
    .map((entry) => `e2e/${entry}`);
  for (const spec of actualSpecs) {
    if (!allAssignedSpecs.has(spec)) {
      throw new Error(`web e2e spec missing taxonomy-backed suite assignment: ${spec}`);
    }
  }

  return {
    entryCount: entries.length,
    familyCount: FAMILIES.length,
  };
}

module.exports = {
  FAMILIES,
  buildTaxonomyRegistry,
  getCorePackageScripts,
  harnessInstallMatrix,
  providerMatrix,
  readWebSuiteMap,
  validateTaxonomyRegistry,
  webSuites,
};
