load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "lib",
    crate_name = "ctx_bundled_assets",
    crate_root = "src/lib.rs",
    edition = "2021",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:tracing",
    ],
)

rust_test(
    name = "unit_tests",
    crate = ":lib",
    deps = [
        "@crates//:tempfile",
    ],
)
