use tokio::sync::broadcast;

use super::{
    AuthHandle, BlobHandle, DaemonHandle, DaemonShutdownHandle, DemoSeedTranscriptHandle,
    DiagnosticsHandle, DictationHandle, ExecutionLaunchHandle, HealthHandle,
    LinuxSandboxRuntimeHandle, LogsHandle, MergeQueueApiHandle, MobileRuntimeHandle,
    MobileSecureProxyHandle, MobileStoreHandle, OrgPolicyHandle, ProviderAccountsHandle,
    ProviderAdminHandle, ProviderAuthImportHandle, ProviderBootstrapHandle,
    ProviderHarnessConfigHandle, ProviderInstallHandle, ProviderOptionsHandle,
    ProviderStatusHandle, ProviderUsageHandle, ProviderWorkspaceAuthHandle, RepoOnboardingHandle,
    RequestBaseHandle, ResourceUtilizationHandle, RunArchiveHandle, SessionArtifactsHandle,
    SessionControlHandle, SessionFileCompletionsHandle, SessionMessageCommandHandle,
    SessionReadModelsHandle, SessionSubagentMcpControlHandle, SessionSubagentMcpReadHandle,
    SessionSubagentReadHandle, SessionTitleModelModeHandle, SessionVcsHandle, SettingsHandle,
    TaskCreationHandle, TaskLifecycleHandle, TaskListingHandle, TaskReadStateHandle,
    TaskSessionAdmissionHandle, TaskSessionListingHandle, TaskTitleHandle, TelemetryHandle,
    TerminalRouteHandle, TitleGenerationLocalHandle, UpdateActivityHandle, UpdateDrainHandle,
    UpdateReleaseHandle, WebSessionRouteHandle, WorkspaceActiveHandle, WorkspaceAttachmentsHandle,
    WorkspaceDeletionHandle, WorkspaceExecutionConfigHandle, WorkspaceFileCompletionsHandle,
    WorkspaceHarnessContainerHandle, WorkspaceMergeQueueConfigHandle, WorkspaceOrgPolicyHandle,
    WorkspacePrimaryBranchHandle, WorkspacePromptBootstrapConfigHandle,
    WorkspaceProviderModelPreferenceHandle, WorkspaceRegistryHandle, WorkspaceStreamHandle,
    WorkspaceVcsStreamHandle, WorkspaceWorktreeHandle,
};

#[derive(Clone)]
pub struct DaemonShutdownSignal {
    shutdown_tx: broadcast::Sender<()>,
}

impl DaemonShutdownSignal {
    pub(in crate::daemon) fn new(shutdown_tx: broadcast::Sender<()>) -> Self {
        Self { shutdown_tx }
    }

    pub fn subscribe(&self) -> broadcast::Receiver<()> {
        self.shutdown_tx.subscribe()
    }
}

#[derive(Clone)]
pub struct DaemonRouteHandles {
    pub auth: AuthHandle,
    pub health: HealthHandle,
    pub diagnostics: DiagnosticsHandle,
    pub blob: BlobHandle,
    pub request_base: RequestBaseHandle,
    pub repo_onboarding: RepoOnboardingHandle,
    pub logs: LogsHandle,
    pub org_policy: OrgPolicyHandle,
    pub workspace_org_policy: WorkspaceOrgPolicyHandle,
    pub workspace_prompt_bootstrap_config: WorkspacePromptBootstrapConfigHandle,
    pub workspace_execution_config: WorkspaceExecutionConfigHandle,
    pub workspace_file_completions: WorkspaceFileCompletionsHandle,
    pub workspace_harness_container: WorkspaceHarnessContainerHandle,
    pub workspace_provider_model_preferences: WorkspaceProviderModelPreferenceHandle,
    pub workspace_worktree: WorkspaceWorktreeHandle,
    pub workspace_registry: WorkspaceRegistryHandle,
    pub workspace_merge_queue_config: WorkspaceMergeQueueConfigHandle,
    pub merge_queue_api: MergeQueueApiHandle,
    pub workspace_attachments: WorkspaceAttachmentsHandle,
    pub workspace_primary_branch: WorkspacePrimaryBranchHandle,
    pub dictation: DictationHandle,
    pub update_release: UpdateReleaseHandle,
    pub update_activity: UpdateActivityHandle,
    pub settings: SettingsHandle,
    pub mobile_store: MobileStoreHandle,
    pub mobile_runtime: MobileRuntimeHandle,
    pub mobile_secure_proxy: MobileSecureProxyHandle,
    pub resource_utilization: ResourceUtilizationHandle,
    pub run_archive: RunArchiveHandle,
    pub session_artifacts: SessionArtifactsHandle,
    pub session_control: SessionControlHandle,
    pub session_file_completions: SessionFileCompletionsHandle,
    pub session_message_command: SessionMessageCommandHandle,
    pub session_read_models: SessionReadModelsHandle,
    pub session_subagent_mcp_read: SessionSubagentMcpReadHandle,
    pub session_subagent_mcp_control: SessionSubagentMcpControlHandle,
    pub session_subagent_read: SessionSubagentReadHandle,
    pub session_title_model_mode: SessionTitleModelModeHandle,
    pub session_vcs: SessionVcsHandle,
    pub demo_seed_transcript: DemoSeedTranscriptHandle,
    pub title_generation_local: TitleGenerationLocalHandle,
    pub task_creation: TaskCreationHandle,
    pub task_lifecycle: TaskLifecycleHandle,
    pub task_listing: TaskListingHandle,
    pub task_read_state: TaskReadStateHandle,
    pub task_session_admission: TaskSessionAdmissionHandle,
    pub task_session_listing: TaskSessionListingHandle,
    pub task_title: TaskTitleHandle,
    pub workspace_deletion: WorkspaceDeletionHandle,
    pub workspace_active: WorkspaceActiveHandle,
    pub workspace_stream: WorkspaceStreamHandle,
    pub workspace_vcs_stream: WorkspaceVcsStreamHandle,
    pub provider_accounts: ProviderAccountsHandle,
    pub provider_auth_import: ProviderAuthImportHandle,
    pub provider_status: ProviderStatusHandle,
    pub provider_admin: ProviderAdminHandle,
    pub provider_install: ProviderInstallHandle,
    pub provider_usage: ProviderUsageHandle,
    pub provider_harness_config: ProviderHarnessConfigHandle,
    pub provider_bootstrap: ProviderBootstrapHandle,
    pub provider_options: ProviderOptionsHandle,
    pub provider_workspace_auth: ProviderWorkspaceAuthHandle,
    pub telemetry: TelemetryHandle,
    pub terminal_route: TerminalRouteHandle,
    pub web_session_route: WebSessionRouteHandle,
    pub execution_launch: ExecutionLaunchHandle,
    pub linux_sandbox_runtime: LinuxSandboxRuntimeHandle,
    pub update_drain: UpdateDrainHandle,
    pub daemon_shutdown: DaemonShutdownHandle,
}

impl DaemonRouteHandles {
    pub(in crate::daemon) fn from_handle(handle: &DaemonHandle) -> Self {
        Self {
            auth: handle.auth(),
            health: handle.health(),
            diagnostics: handle.diagnostics(),
            blob: handle.blob(),
            request_base: handle.request_base(),
            repo_onboarding: handle.repo_onboarding(),
            logs: handle.logs(),
            org_policy: handle.org_policy(),
            workspace_org_policy: handle.workspace_org_policy(),
            workspace_prompt_bootstrap_config: handle.workspace_prompt_bootstrap_config(),
            workspace_execution_config: handle.workspace_execution_config(),
            workspace_file_completions: handle.workspace_file_completions(),
            workspace_harness_container: handle.workspace_harness_container(),
            workspace_provider_model_preferences: handle.workspace_provider_model_preferences(),
            workspace_worktree: handle.workspace_worktree(),
            workspace_registry: handle.workspace_registry(),
            workspace_merge_queue_config: handle.workspace_merge_queue_config(),
            merge_queue_api: handle.merge_queue_api(),
            workspace_attachments: handle.workspace_attachments(),
            workspace_primary_branch: handle.workspace_primary_branch(),
            dictation: handle.dictation(),
            update_release: handle.update_release(),
            update_activity: handle.update_activity(),
            settings: handle.settings(),
            mobile_store: handle.mobile_store(),
            mobile_runtime: handle.mobile_runtime(),
            mobile_secure_proxy: handle.mobile_secure_proxy(),
            resource_utilization: handle.resource_utilization(),
            run_archive: handle.run_archive(),
            session_artifacts: handle.session_artifacts(),
            session_control: handle.session_control(),
            session_file_completions: handle.session_file_completions(),
            session_message_command: handle.session_message_command(),
            session_read_models: handle.session_read_models(),
            session_subagent_mcp_read: handle.session_subagent_mcp_read(),
            session_subagent_mcp_control: handle.session_subagent_mcp_control(),
            session_subagent_read: handle.session_subagent_read(),
            session_title_model_mode: handle.session_title_model_mode(),
            session_vcs: handle.session_vcs(),
            demo_seed_transcript: handle.demo_seed_transcript(),
            title_generation_local: handle.title_generation_local(),
            task_creation: handle.task_creation(),
            task_lifecycle: handle.task_lifecycle(),
            task_listing: handle.task_listing(),
            task_read_state: handle.task_read_state(),
            task_session_admission: handle.task_session_admission(),
            task_session_listing: handle.task_session_listing(),
            task_title: handle.task_title(),
            workspace_deletion: handle.workspace_deletion(),
            workspace_active: handle.workspace_active(),
            workspace_stream: handle.workspace_stream(),
            workspace_vcs_stream: handle.workspace_vcs_stream(),
            provider_accounts: handle.provider_accounts(),
            provider_auth_import: handle.provider_auth_import(),
            provider_status: handle.provider_status(),
            provider_admin: handle.provider_admin(),
            provider_install: handle.provider_install(),
            provider_usage: handle.provider_usage(),
            provider_harness_config: handle.provider_harness_config(),
            provider_bootstrap: handle.provider_bootstrap(),
            provider_options: handle.provider_options(),
            provider_workspace_auth: handle.provider_workspace_auth(),
            telemetry: handle.telemetry(),
            terminal_route: handle.terminal_route(),
            web_session_route: handle.web_session_route(),
            execution_launch: handle.execution_launch(),
            linux_sandbox_runtime: handle.linux_sandbox_runtime(),
            update_drain: handle.update_drain(),
            daemon_shutdown: handle.daemon_shutdown(),
        }
    }
}
