#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")"/../../../.. && pwd)"

if [[ "$(uname -s)" == "Darwin" && -z "${CN_API_KEY:-}" ]]; then
  echo "error: CN_API_KEY is required on macOS for desktop automation." >&2
  exit 1
fi

run_case() {
  local name="$1"
  shift
  echo
  echo "==> ${name}"
  (cd "$ROOT" && env "$@" pnpm -C core/apps/desktop test:automation)
}

BASE_ENV=(
  "CTX_AUTOMATION_SKIP_APP_BUILD=${CTX_AUTOMATION_SKIP_APP_BUILD:-1}"
  "CTX_AUTOMATION_USE_EXTERNAL_DAEMON=${CTX_AUTOMATION_USE_EXTERNAL_DAEMON:-0}"
)

run_case "local matrix" \
  "${BASE_ENV[@]}" \
  "CTX_AUTOMATION_SCENARIOS=${CTX_AUTOMATION_LOCAL_SCENARIOS:-local}"

if [[ -n "${CTX_AUTOMATION_REMOTE_HOST:-}" ]]; then
  run_case "remote host matrix" \
    "${BASE_ENV[@]}" \
    "CTX_AUTOMATION_SCENARIOS=${CTX_AUTOMATION_REMOTE_HOST_SCENARIOS:-remote-host}" \
    "CTX_AUTOMATION_REMOTE_CTX_BIN=${CTX_AUTOMATION_REMOTE_CTX_BIN:-/tmp/ctx-e2e-bin/ctx}" \
    "CTX_AUTOMATION_REMOTE_HOST=${CTX_AUTOMATION_REMOTE_HOST}" \
    "CTX_AUTOMATION_REMOTE_USER=${CTX_AUTOMATION_REMOTE_USER:-devboxadmin}" \
    "CTX_AUTOMATION_REMOTE_PASSWORD=${CTX_AUTOMATION_REMOTE_PASSWORD:-}" \
    "CTX_AUTOMATION_REMOTE_PORT=${CTX_AUTOMATION_REMOTE_PORT:-44099}" \
    "CTX_AUTOMATION_REMOTE_DATA_DIR=${CTX_AUTOMATION_REMOTE_DATA_DIR:-/tmp/ctx-e2e-remote/daemon}" \
    "CTX_AUTOMATION_SSH_NO_START_REMOTE=${CTX_AUTOMATION_SSH_NO_START_REMOTE:-0}"
fi

if [[ -n "${CTX_AUTOMATION_REMOTE_CONTAINER_HOST:-}" ]]; then
  run_case "remote container matrix" \
    "${BASE_ENV[@]}" \
    "CTX_AUTOMATION_SCENARIOS=${CTX_AUTOMATION_REMOTE_CONTAINER_SCENARIOS:-remote-container}" \
    "CTX_AUTOMATION_REMOTE_CTX_BIN=${CTX_AUTOMATION_REMOTE_CTX_BIN:-/tmp/ctx-e2e-bin/ctx}" \
    "CTX_AUTOMATION_REMOTE_HOST=${CTX_AUTOMATION_REMOTE_CONTAINER_HOST}" \
    "CTX_AUTOMATION_REMOTE_USER=${CTX_AUTOMATION_REMOTE_CONTAINER_USER:-${CTX_AUTOMATION_REMOTE_USER:-devboxadmin}}" \
    "CTX_AUTOMATION_REMOTE_PASSWORD=${CTX_AUTOMATION_REMOTE_CONTAINER_PASSWORD:-${CTX_AUTOMATION_REMOTE_PASSWORD:-}}" \
    "CTX_AUTOMATION_REMOTE_PORT=${CTX_AUTOMATION_REMOTE_CONTAINER_PORT:-44199}" \
    "CTX_AUTOMATION_REMOTE_DATA_DIR=${CTX_AUTOMATION_REMOTE_CONTAINER_DATA_DIR:-/tmp/ctx-e2e-remote-container/daemon}" \
    "CTX_AUTOMATION_SSH_NO_START_REMOTE=${CTX_AUTOMATION_SSH_NO_START_REMOTE:-0}"
fi
