#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");
const { pathToFileURL } = require("node:url");

const coreRoot = path.resolve(__dirname, "..");
const defaultBaseMatrix = path.join(coreRoot, "crates", "ctx-provider-accounts", "src", "provider_matrix.json");

const resolveInputPath = (raw) => {
  const value = String(raw || "").trim();
  if (!value) return "";
  if (path.isAbsolute(value)) return value;
  const fromCwd = path.resolve(process.cwd(), value);
  if (fs.existsSync(fromCwd)) return fromCwd;
  return path.resolve(coreRoot, value);
};

const resolveOutputPath = (raw) => {
  const value = String(raw || "").trim();
  if (!value) return "";
  if (path.isAbsolute(value)) return value;
  return path.resolve(process.cwd(), value);
};

const parseArgs = (argv) => {
  const opts = {
    matrix: defaultBaseMatrix,
    index: "",
    out: "",
    artifactBaseUrl: "",
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--matrix") {
      opts.matrix = resolveInputPath(argv[i + 1]);
      i += 1;
      continue;
    }
    if (arg === "--index") {
      opts.index = resolveInputPath(argv[i + 1]);
      i += 1;
      continue;
    }
    if (arg === "--out") {
      opts.out = resolveOutputPath(argv[i + 1]);
      i += 1;
      continue;
    }
    if (arg === "--artifact-base-url") {
      opts.artifactBaseUrl = String(argv[i + 1] || "").trim();
      i += 1;
      continue;
    }
    if (arg === "--help" || arg === "-h") {
      opts.help = true;
      continue;
    }
    throw new Error(`unsupported argument: ${arg}`);
  }
  if (!opts.out && opts.index) {
    opts.out = path.join(path.dirname(opts.index), "provider_matrix.generated.json");
  }
  return opts;
};

const readJson = (filePath, label) => {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (error) {
    throw new Error(`failed to parse ${label} at ${filePath}: ${error?.message || String(error)}`);
  }
};

const normalizeMatrixOsToken = (raw) => {
  const value = String(raw || "").trim().toLowerCase();
  if (value === "macos" || value === "darwin") return "darwin";
  return value;
};

const targetKeys = ({ os, arch }) => {
  const normalizedOs = normalizeMatrixOsToken(os);
  const normalizedArch = String(arch || "").trim().toLowerCase();
  const keys = [`${normalizedOs}-${normalizedArch}`];
  // Keep macOS alias keys during transition so tooling that still probes macos-* keeps working.
  if (normalizedOs === "darwin") {
    keys.push(`macos-${normalizedArch}`);
  }
  return keys;
};

const normalizeUrl = ({ entry, artifactBaseUrl, indexDir }) => {
  if (artifactBaseUrl) {
    const prefix = artifactBaseUrl.endsWith("/") ? artifactBaseUrl.slice(0, -1) : artifactBaseUrl;
    const sha256 = String(entry.sha256 || "").trim().toLowerCase();
    if (!sha256) {
      throw new Error(
        `provider ${String(entry.provider_id || "<unknown>")} target ${String(entry.os || "<unknown>")}/${String(entry.arch || "<unknown>")} missing sha256`,
      );
    }
    const artifactProviderId = String(entry.artifact_provider_id || entry.provider_id || "").trim();
    return `${prefix}/${artifactProviderId}/${entry.version}/${entry.os}/${entry.arch}/sha256/${sha256}/${entry.filename}`;
  }
  const artifactPath = String(entry.artifact_path || "").trim();
  const artifactRelPath = String(entry.artifact_rel_path || "").trim();
  const absolute = artifactPath
    ? path.resolve(artifactPath)
    : artifactRelPath
      ? path.resolve(indexDir || process.cwd(), artifactRelPath)
      : "";
  if (!absolute) {
    throw new Error(
      `provider ${String(entry.provider_id || "<unknown>")} target ${String(entry.os || "<unknown>")}/${String(entry.arch || "<unknown>")} missing artifact_path/artifact_rel_path`,
    );
  }
  return pathToFileURL(absolute).href;
};

const upsertRelease = ({ provider, version }) => {
  if (!Array.isArray(provider.releases)) {
    provider.releases = [];
  }
  const existing = provider.releases.find((release) => release && release.version === version);
  if (existing) {
    existing.status = existing.status || "supported";
    return;
  }
  provider.releases = [
    {
      version,
      status: "supported",
      notes: "generated by provider_deps_matrix_overlay.cjs",
    },
    ...provider.releases,
  ];
};

const managedInstallSupportsStagedTargets = (managedInstall) => {
  const kind = String(managedInstall?.kind || "").trim().toLowerCase();
  return kind === "archive" || kind === "npm" || kind === "python";
};

const applyIndexOverlay = ({ matrix, index, indexDir, artifactBaseUrl }) => {
  const providers = Array.isArray(matrix.providers) ? matrix.providers : [];
  const byId = new Map(
    providers
      .filter((provider) => provider && typeof provider === "object" && typeof provider.id === "string")
      .map((provider) => [provider.id, provider]),
  );
  const entries = Array.isArray(index.providers) ? index.providers : [];
  const errors = [];

  for (const entry of entries) {
    const providerId = String(entry?.provider_id || "").trim();
    const version = String(entry?.version || "").trim();
    if (!providerId || !version) continue;
    const provider = byId.get(providerId);
    if (!provider) {
      errors.push(`provider missing in matrix: ${providerId}`);
      continue;
    }
    const managedInstall =
      provider.managed_install && typeof provider.managed_install === "object"
        ? provider.managed_install
        : null;
    if (!managedInstall || !managedInstallSupportsStagedTargets(managedInstall)) {
      errors.push(
        `provider ${providerId} must be managed_install.kind=archive|npm|python to apply staged target`,
      );
      continue;
    }

    if (!managedInstall.targets || typeof managedInstall.targets !== "object") {
      managedInstall.targets = {};
    }
    managedInstall.version = version;

    const keys = targetKeys({ os: entry.os, arch: entry.arch });
    let url;
    try {
      url = normalizeUrl({ entry, artifactBaseUrl, indexDir });
    } catch (error) {
      errors.push(String(error?.message || error));
      continue;
    }
    const target = {
      url,
      archive: String(entry.archive || "tar_gz"),
      bin_path: String(entry.bin_path || "").trim(),
      sha256: String(entry.sha256 || "").trim(),
    };
    if (entry.launch) target.launch = String(entry.launch);

    if (!target.bin_path) {
      errors.push(`provider ${providerId} target ${keys[0]} missing bin_path`);
      continue;
    }

    for (const key of keys) {
      managedInstall.targets[key] = { ...target };
    }
    upsertRelease({ provider, version });
  }

  return { errors };
};

const main = () => {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help) {
    console.log(
      [
        "Usage: node core/scripts/provider_deps_matrix_overlay.cjs --index <index.json> [options]",
        "",
        "Options:",
        "  --matrix <path>             Base provider matrix JSON",
        "  --index <path>              provider_deps_index.json input",
        "  --out <path>                Output matrix path",
        "  --artifact-base-url <url>   Rewrite artifact URLs to immutable publish prefix",
      ].join("\n"),
    );
    return;
  }

  if (!opts.index) {
    throw new Error("--index is required");
  }
  if (!opts.out) {
    throw new Error("--out is required");
  }

  const matrix = readJson(opts.matrix, "provider matrix");
  const index = readJson(opts.index, "provider deps index");
  const indexDir = path.dirname(opts.index);
  const { errors } = applyIndexOverlay({
    matrix,
    index,
    indexDir,
    artifactBaseUrl: opts.artifactBaseUrl,
  });

  if (errors.length > 0) {
    for (const error of errors) {
      console.error(`error: ${error}`);
    }
    process.exit(1);
  }

  matrix.generated_at = new Date().toISOString();
  fs.mkdirSync(path.dirname(opts.out), { recursive: true });
  fs.writeFileSync(opts.out, `${JSON.stringify(matrix, null, 2)}\n`, "utf8");
  console.log(`wrote matrix: ${opts.out}`);
};

if (require.main === module) {
  main();
}

module.exports = {
  normalizeMatrixOsToken,
  targetKeys,
  normalizeUrl,
  applyIndexOverlay,
};
