export const spacing = {
  screenPadding: 20,
  screenPaddingWide: 22,
  sectionSpacing: 20,
  panelPadding: 16,
  panelRadius: 22,
  fieldRadius: 14,
  buttonRadius: 16,
  pillRadius: 999,
  messageSpacing: 14,
  messageTopPadding: 10,
  messageBottomPadding: 8,
  composerRadius: 28,
  composerInnerHorizontal: 16,
  composerInnerVertical: 14,
  composerToolSize: 36,
  composerPrimarySize: 40,
} as const;
