[package]
name = "ctx-workspace-stream-service"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-trait.workspace = true
ctx-core = { path = "../ctx-core" }
ctx-workspace-active-snapshot = { path = "../ctx-workspace-active-snapshot" }

[dev-dependencies]
chrono.workspace = true
tokio.workspace = true
